function Hd = bandpasslow
%BANDPASSLOW Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the Signal Processing Toolbox 7.0.
% Generated on: 27-Aug-2015 14:09:45

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
Fs = 32000;  % Sampling Frequency

Fpass = 250;         % Passband Frequency
Fstop = 260;         % Stopband Frequency
Apass = 1;           % Passband Ripple (dB)
Astop = 80;          % Stopband Attenuation (dB)
match = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop, Fs);
Hdlo = design(h, 'butter', 'MatchExactly', match);

% [EOF]
