function Hd = decimationLevel1Factor8Hz32k
%DECIMATIONLEVEL1FACTOR8HZ32K Returns a multirate filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the Signal Processing Toolbox 7.0.
% Generated on: 03-Sep-2015 22:28:17

decf = 8;                     % Decimation Factor

Hd  = mfilt.firdecim(decf);

% [EOF]
% downsampled to 500 Hz
figure;
plot(filter(hdec,filter(hdec,data(5,:))));
%then we need to filter bandpass or cut it down to 250 Hz
