function Hd = filterCheetahLowPass
%FILTERCHEETAHLOWPASS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the Signal Processing Toolbox 7.0.
% Generated on: 06-Aug-2015 16:22:04

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 32000;  % Sampling Frequency
N    = 31;       % Order
Fc   = 6000;     % Cutoff Frequency
flag = 'scale';  % Sampling Flag
% Create the window vector for the design algorithm.
win = bartlett(N+1);
% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'low', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
