function Hd = filterDesignForCheetah
%FILTERDESIGNFORCHEETAH Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the Signal Processing Toolbox 7.0.
% Generated on: 06-Aug-2015 15:55:21

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 32000;  % Sampling Frequency

N    = 63;       % Order
Fc1  = 600;      % First Cutoff Frequency
Fc2  = 6000;     % Second Cutoff Frequency
flag = 'scale';  % Sampling Flag
% Create the window vector for the design algorithm.
win = bartlett(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, [Fc1 Fc2]/(Fs/2), 'bandpass', win, flag);
Hd = dsp.FIRFilter( ...
    'Numerator', b);

% [EOF]
