function Hd = hilbertFilterFunction
%HILBERTFILTERFUNCTION Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the Signal Processing Toolbox 7.0.
% Generated on: 03-Mar-2016 19:06:37

% Equiripple Hilbert transformer filter designed using the FIRPM function.

% All frequency values are normalized to 1.

N = 10;          % Order
F = [0.05 0.95];  % Frequency Vector
A = [1 1];        % Amplitude Vector
W = 1;            % Weight Vector

b  = firpm(N, F, A, W, 'hilbert');
Hd = dfilt.dffir(b);

% [EOF]
