function Hd = miscfilteriir
%MISCFILTERIIR Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the Signal Processing Toolbox 7.0.
% Generated on: 02-Mar-2016 01:00:25

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
Fs = 32000;  % Sampling Frequency

Fpass = 125;         % Passband Frequency
Fstop = 250;         % Stopband Frequency
Apass = 1;           % Passband Ripple (dB)
Astop = 30;          % Stopband Attenuation (dB)
match = 'passband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
htest  = fdesign.lowpass(Fpass, Fstop, Apass, Astop, Fs);
Hdtest = design(h, 'butter', 'MatchExactly', match);

% [EOF]
