function Hd = swrBandpassFrank
%SWRBANDPASSFRANK Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the Signal Processing Toolbox 7.0.
% Generated on: 06-Aug-2015 17:35:33

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 32000;  % Sampling Frequency

N   = 20;   % Order
Fc1 = 100;  % First Cutoff Frequency
Fc2 = 250;  % Second Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass('N,F3dB1,F3dB2', N, Fc1, Fc2, Fs);
Hdswr = design(h, 'butter');

% [EOF]

%Buzsaki style would be  a 100-250 Hz filter. seems to produce nice packets
%of SWRfor enveloping

% Frank used a 100-400 Hz filter for his online detection work.