clear all;
close all;




/Users/andrewhowe/Downloads/da5fscEphysRecheck

52/pi
[ correctedCsc, idxs, mxValues, meanCscWindow ] = cscCorrection( data(5,:)', timestamps );


figure; plot((1:3200)/32,meanCscWindow*0.000015624999960550667); title('avg fscv artifact, raw, unfiltered data'); xlabel('time'); ylabel('mV')




cm=[0	0	0;...
0	255	0;...
0	250	0;...
0	245	0;...
0	240	0;...
0	235	0;...
0	230	0;...
0	227	0;...
0	224	0;...
0	220	0;...
0	216	0;...
0	212	0;...
0	208	0;...
0	203	0;...
0	199	0;...
0	195	0;...
0	190	0;...
0	184	0;...
0	181	0;...
0	176	0;...
0	172	0;...
0	168	0;...
0	164	0;...
0	160	0;...
0	154	0;...
0	150	0;...
0	146	0;...
0	142	0;...
0	138	0;...
0	134	0;...
0	132	0;...
0	130	0;...
0	132	8;...
0	134	16;...
0	136	25;...
0	139	30;...
0	142	35;...
0	144	40;...
0	146	45;...
0	149	50;...
0	152	61;...
0	155	72;...
0	159	79;...
0	162	88;...
0	165	106;...
0	168	114;...
0	172	120;...
0	177	128;...
6	170	129;...
12	165	130;...
16	158	131;...
20	150	132;...
24	144	133;...
28	138	134;...
32	135	135;...
38	132	136;...
44	121	136;...
55	110	136;...
63	95	136;...
70	85	136;...
80	75	136;...
89	65	136;...
92	48	136;...
95	42	136;...
110	37	136;...
118	20	110;...
125	10	90;...
136	4	76;...
76	7	76;...
82	13	76;...
80	20	62;...
93	27	51;...
106	34	40;...
112	38	32;...
118	43	28;...
124	50	25;...
130	56	13;...
136	64	11;...
141	51	0;...
147	60	0;...
157	75	0;...
163	93	0;...
168	101	0;...
172	108	0;...
176	116	0;...
180	123	0;...
184	131	0;...
188	138	0;...
192	146	0;...
196	153	0;...
200	161	0;...
204	168	0;...
208	176	0;...
212	183	0;...
216	191	0;...
220	198	0;...
224	206	0;...
228	213	0;...
233	221	0;...
235	229	0;...
238	238	0;...
240	240	0;...
0	0	7;...
0	0	14;...
0	0	21;...
0	0	28;...
0	0	35;...
0	0	42;...
0	0	49;...
0	0	56;...
0	0	63;...
0	0	70;...
0	0	77;...
0	0	84;...
0	0	91;...
0	0	98;...
0	0	105;...
0	0	112;...
0	0	119;...
0	0	126;...
0	0	133;...
0	0	140;...
0	0	147;...
0	0	154;...
0	0	161;...
0	0	168;...
0	0	175;...
0	0	182;...
0	0	189;...
0	0	196;...
0	0	203;...
0	0	210;...
0	0	217;...
0	0	224;...
0	0	231;...
0	0	236;...
0	0	0];

cm=cm/255;

%% clean calibration
% Initialize variables.
filename = '/Users/andrewhowe/blairLab/nrsa2016/fscvExamplesForNRSA/calib_da5_day2_ch1_b35-1_00um-c-bg.csv';
delimiter = ',';
% FORMAT For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';
% Open the text file.
fileID = fopen(filename,'r');
% Read columns of data according to format string.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN, 'ReturnOnError', false);
% Close the text file.
fclose(fileID);
% Create output variable
fscvData = [dataArray{1:end-1}];
% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;
% Analyze
fscvData=fscvData';
background=median(fscvData')';
%signal=calibda5day2ch1b35100umcbg;
for idx=1:250
    signal(:,idx)=fscvData(:,idx)-background;
end
cvtime=(1:250)/10;
wrappedVolts=[1:500 500:-1:1];
%figure; surf(signal); colormap(build_NOAA_colorgradient); colorbar;
figure; 
subplot(1,3,1);
imagesc(flipud(signal)); 
colormap(flipud(cm)); 
colorbar; xlabel('sweep'); ylabel('sample'); title('colormap');
subplot(1,3,2);
plot(cvtime,signal(302,:)); ylabel('current (nA)'); xlabel('time (s)'); axis([ 0 25 -10 35 ]); title('DA trace');
subplot(1,3,3);
plot(wrappedVolts,signal(:,100)); axis([ -4 505 -15 35 ]); xlabel('point'); ylabel('current (nA)'); title('peak DA CV');




figure;subplot(2,2,1);
plot(wrappedVolts,fscvData(:,100), 'k'); hold on;
plot(wrappedVolts,background, 'r');
plot(wrappedVolts,signal(:,100),'b'); 
axis([ -4 505 -800 800 ]); xlabel('sample'); ylabel('current (nA)'); title('DA CV');
legend('total','background','DA')
subplot(2,2,2);
plot(wrappedVolts,fscvData(:,100), 'k'); axis([ -4 505 -800 800 ]); xlabel('sample'); ylabel('current (nA)'); title('peak total CV');
subplot(2,2,3);
plot(wrappedVolts,background,'r'); axis([ -4 505 -800 800 ]); xlabel('sample'); ylabel('current (nA)'); title('peak background CV');
subplot(2,2,4);
plot(wrappedVolts,signal(:,100),'b'); axis([ -4 505 -15 35 ]); xlabel('sample'); ylabel('current (nA)'); title('peak DA CV');



smCax=[-1.5, 3];

%% no cage noise test in rat
% Initialize variables.
%filename = '/Users/andrewhowe/Desktop/fscvExamplesForNRSA/nocage_v4_platterseq2_100112_bg.csv';
filename = '/Users/andrewhowe/toSort/uclaDoctoralProgram/grants/nrsa2016/fscvExamplesForNRSA/nocage_v4_platterseq2_100112_bg.csv';
delimiter = ',';
% FORMAT For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';
% Open the text file.
fileID = fopen(filename,'r');
% Read columns of data according to format string.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN, 'ReturnOnError', false);
% Close the text file.
fclose(fileID);
% Create output variable
fscvData = [dataArray{1:end-1}];
% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;
% Analyze
fscvData=fscvData';
background=median(fscvData')';
%signal=calibda5day2ch1b35100umcbg;
for idx=1:150
    signal(:,idx)=fscvData(:,idx)-background;
end
signal=signal(:,1:150);
cvtime=(1:150)/10;
wrappedVolts=[1:500 500:-1:1];
%figure; surf(signal); colormap(build_NOAA_colorgradient); colorbar;
figure; 
subplot(1,3,1);
imagesc(flipud(signal)); colormap(buildFscvColormap); colorbar; caxis(smCax); xlabel('sweep'); ylabel('sample'); title('colormap'); %colormap(build_NOAA_colorgradient);
subplot(1,3,2);
plot(cvtime,signal(302,:)); ylabel('current (nA)'); xlabel('time (s)'); axis([ 0 15 -1 1 ]); title('DA trace');
subplot(1,3,3);
plot(wrappedVolts,signal(:,50)); axis([ -4 505 -1 1 ]); xlabel('point'); ylabel('current (nA)'); title('peak DA CV');




%% noise test in rat in faraday cage
% Initialize variables.
%filename = '/Volumes/SILVRSURFER/fscvExamplesForNRSA/fcage_da5_day0_dch2-test-all-back-faraday-no-wall-ground_bg.csv';
%filename = '/Users/andrewhowe/Desktop/fscvExamplesForNRSA/fcage_da5_day0_dch2-test-all-back-faraday-no-wall-ground_bgSubtracted.csv';
filename = '/Users/andrewhowe/toSort/uclaDoctoralProgram/grants/nrsa2016/fscvExamplesForNRSA/fcage_da5_day0_dch2-test-all-back-faraday-no-wall-ground_bgSubtracted.csv';
% FORMAT For more information, see the TEXTSCAN documentation.
delimiter = ',';
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';
% Open the text file.
fileID = fopen(filename,'r');
% Read columns of data according to format string.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN, 'ReturnOnError', false);
% Close the text file.
fclose(fileID);
% Create output variable
fscvData = [dataArray{1:end-1}];
% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;
% Analyze
fscvData=fscvData';
background=median(fscvData')';
%signal=calibda5day2ch1b35100umcbg;
for idx=1:150
    signal(:,idx)=fscvData(:,idx)-background;
end
cvtime=(1:150)/10;
wrappedVolts=[1:500 500:-1:1];
%figure; surf(signal); colormap(build_NOAA_colorgradient); colorbar;
figure; 
subplot(1,3,1);
imagesc(flipud(fscvData)); colormap(flipud(buildFscvColormap)); colorbar; xlabel('sweep'); ylabel('sample'); title('colormap'); %colormap(build_NOAA_colorgradient);
subplot(1,3,2);
plot(cvtime, fscvData(302,:)); ylabel('current (nA)'); xlabel('time (s)'); axis([ 0 15 -1 1 ]); title('DA trace');
subplot(1,3,3);
plot(wrappedVolts,fscvData(:,145)); axis([ -4 505 -1 1 ]); xlabel('point'); ylabel('current (nA)'); title('peak DA CV');


return;


% get the lag
basedir='/Users/andrewhowe/blairLab/blairlab_data/v4/march5_twotasks1/';
alignmentLag=getFscvNlxAlignmentLag([basedir '/fscv/platter/'],[basedir '/nlx/platter/'],7)

% load the fscv data
daConc=loadTarheelCsvData([basedir '/fscv/platter/'],.993);


% get the video data and fix it
[xpos, ypos, xyPositionTimestamps, angles, header ] = nvt2mat([basedir '/nlx/platter/VT0.nvt']);
xpos=nlxPositionFixer(xpos);
ypos=nlxPositionFixer(ypos);

% calculate velocity
velocity=sqrt(cast(((diff(xpos)).^2+(diff(ypos)).^2), 'double'));

[ events, eventTimestamps   ] = nev2mat([ basedir '/nlx/platter/Events.nev']);

% 
zoneZeroIdxs=find(not(cellfun('isempty', strfind(events, 'Zoned Video: Zone0 Entered') )));
zoneZeroIdxs=[zoneZeroIdxs; find(not(cellfun('isempty', strfind(events, 'Zoned Video: Zone0 Exited') )))];
vidIdxZoneZero=zeros(length(zoneZeroIdxs),1);
for idx=1:length((zoneZeroIdxs))
    vidIdxZoneZero(idx) = min(find((eventTimestamps(zoneZeroIdxs(idx))<xyPositionTimestamps)));
end
% find 
zoneOneIdxs=find(not(cellfun('isempty', strfind(events, 'Zoned Video: Zone1 Entered') )));
zoneOneIdxs=[zoneOneIdxs; find(not(cellfun('isempty', strfind(events, 'Zoned Video: Zone1 Exited') )))];
vidIdxZoneOne=zeros(length(zoneOneIdxs),1);
for idx=1:length((zoneOneIdxs))
    vidIdxZoneOne(idx) = min(find((eventTimestamps(zoneOneIdxs(idx))<xyPositionTimestamps)));
end
% find 
zoneTwoIdxs=find(not(cellfun('isempty', strfind(events, 'Zoned Video: Zone2 Entered') )));
zoneTwoIdxs=[zoneTwoIdxs; find(not(cellfun('isempty', strfind(events, 'Zoned Video: Zone2 Exited') )))];
vidIdxZoneTwo=zeros(length(zoneTwoIdxs),1);
for idx=1:length((zoneTwoIdxs))
    vidIdxZoneTwo(idx) = min(find((eventTimestamps(zoneTwoIdxs(idx))<xyPositionTimestamps)));
end
% find 
zoneThreeIdxs=find(not(cellfun('isempty', strfind(events, 'Zoned Video: Zone3 Entered') )));
zoneThreeIdxs=[zoneThreeIdxs; find(not(cellfun('isempty', strfind(events, 'Zoned Video: Zone3 Exited') )))];
vidIdxZoneThree=zeros(length(zoneThreeIdxs),1);
for idx=1:length((zoneThreeIdxs))
    vidIdxZoneThree(idx) = min(find((eventTimestamps(zoneThreeIdxs(idx))<xyPositionTimestamps)));
end
% find 
zoneFourIdxs=find(not(cellfun('isempty', strfind(events, 'Zoned Video: Zone4 Entered') )));
zoneFourIdxs=[zoneFourIdxs; find(not(cellfun('isempty', strfind(events, 'Zoned Video: Zone4 Exited') )))];
vidIdxZoneFour=zeros(length(zoneFourIdxs),1);
for idx=1:length((zoneFourIdxs))
    vidIdxZoneFour(idx) = min(find((eventTimestamps(zoneFourIdxs(idx))<xyPositionTimestamps)));
end
% find 
zoneFiveIdxs=find(not(cellfun('isempty', strfind(events, 'Zoned Video: Zone5 Entered') )));
zoneFiveIdxs=[zoneFiveIdxs; find(not(cellfun('isempty', strfind(events, 'Zoned Video: Zone5 Exited') )))];
vidIdxZoneFive=zeros(length(zoneOneIdxs),1);
for idx=1:length((zoneFiveIdxs))
    vidIdxZoneFive(idx) = min(find((eventTimestamps(zoneFiveIdxs(idx))<xyPositionTimestamps)));
end
% find 
pelletIdxs=find(not(cellfun('isempty', strfind(events, 'TTL Output on PCI-DIO24_0 board 0 port 2 value (0x0007).') )));
vidIdxZonePellet=zeros(length(pelletIdxs),1);
for idx=1:length((pelletIdxs))
    vidIdxZonePellet(idx) = min(find((eventTimestamps(pelletIdxs(idx))<xyPositionTimestamps)));
end


figure;hold off;plot( xpos, ypos, 'Color', [  0 0 0 .2] );hold on;
plot( xpos(vidIdxZoneZero), ypos(vidIdxZoneZero), 'co', 'MarkerSize', 2 );
plot( xpos(vidIdxZoneOne), ypos(vidIdxZoneOne), 'ko', 'MarkerSize', 2 );
plot( xpos(vidIdxZoneTwo), ypos(vidIdxZoneTwo), 'go', 'MarkerSize', 2 );
plot( xpos(vidIdxZoneThree), ypos(vidIdxZoneThree), 'mo', 'MarkerSize', 2 );
plot( xpos(vidIdxZoneFour), ypos(vidIdxZoneFour), 'yo', 'MarkerSize', 2 );
plot( xpos(vidIdxZonePellet), ypos(vidIdxZonePellet), 'r+', 'MarkerSize', 2 );
plot( xpos(tempNlxIdxs), ypos(tempNlxIdxs), 'b');

zw=zeros(1,length(zoneZeroIdxs)); on=ones(1,length(zoneOneIdxs)); tw=ones(1, length(length(zoneTwoIdxs)))*2; pe=ones(length(pelletIdxs))*-1;
figure; hold on; 
plot( (eventTimestamps(zoneZeroIdxs)-eventTimestamps(1))/60e6, zw, 'c*');
plot( (eventTimestamps(zoneOneIdxs)-eventTimestamps(1))/60e6, on, 'k*');
plot( (eventTimestamps(zoneTwoIdxs)-eventTimestamps(1))/60e6, tw, 'g*');
plot( (eventTimestamps(pelletIdxs)-eventTimestamps(1))/60e6, pe, 'ro');

% sfn 2015 FSCV data information -- the favorite colorplot
%14:18.1 and 14:44.
startMinute=14.1; endMinute=14.8;
tempNlxIdxs=min(find(((xyPositionTimestamps-xyPositionTimestamps(1))/(60e6))>startMinute)):max(find(((xyPositionTimestamps-xyPositionTimestamps(1))/(60e6))<endMinute));
tempDaIdxs = (ceil(startMinute*600):ceil(endMinute*600))+alignmentLag;
eventIdxs = min(find(eventTimestamps>xyPositionTimestamps(tempNlxIdxs(1)))):min(find(eventTimestamps>xyPositionTimestamps(tempNlxIdxs(end))));
figure; hold on; subplot(3,1,1); plot((tempDaIdxs)/600, (daConc(tempDaIdxs)-min(daConc(tempDaIdxs)))/(max(daConc(tempDaIdxs)-min(daConc(tempDaIdxs)))), 'Color', [ .7 .1 .8 ]); 
tempVelocity=sqrt(cast(((diff(xpos(tempNlxIdxs))).^2+(diff(ypos(tempNlxIdxs))).^2), 'double'));
tempTimePrime=(alignmentLag/600)+(tempNlxIdxs(1:end-1)/(3*600)+mean(diff(tempNlxIdxs/(60*30))));
subplot(3,1,1); plot(tempTimePrime, (tempVelocity-min(tempVelocity))/max(tempVelocity-min(tempVelocity)), 'Color', [ .1 .8 .4 ] ); legend('\Delta DA (nM)', 'velocity'); axis tight;
subplot(3,1,2); plot((alignmentLag/600)+tempNlxIdxs/(60*30), distFromPoint( xpos(tempNlxIdxs), ypos(tempNlxIdxs), 367, 121 )); %legend('dist from lower');
hold on;plot((alignmentLag/600)+tempNlxIdxs/(60*30), distFromPoint( xpos(tempNlxIdxs), ypos(tempNlxIdxs), 376, 376 )); legend('dist from lower','dist from upper'); axis tight;
subplot(3,1,3); plot((alignmentLag/600)+tempNlxIdxs/(60*30), xpos(tempNlxIdxs)); hold on; plot((alignmentLag/600)+tempNlxIdxs/(60*30), ypos(tempNlxIdxs)); axis tight; %legend('dist from lower');
% distance from any reward pot
topRewardDistance=distFromPoint( xpos(tempNlxIdxs), ypos(tempNlxIdxs), 367, 121 );
bottomRewardDistance=distFromPoint( xpos(tempNlxIdxs), ypos(tempNlxIdxs), 376, 376 );
anyRewardDistance=min(topRewardDistance, bottomRewardDistance);
subplot(3,1,1); hold on; plot((alignmentLag/600)+tempNlxIdxs/(60*30), anyRewardDistance/max(anyRewardDistance));
% distance to trigger
triggerRewardDistance=distFromPoint( xpos(tempNlxIdxs), ypos(tempNlxIdxs), 499, 286 );
subplot(3,1,2); plot( (alignmentLag/600)+tempNlxIdxs/(60*30) , triggerRewardDistance);

figure; x = decimate(xpos(tempNlxIdxs), 3)'; y = decimate(ypos(tempNlxIdxs), 3)'; z = daConc(tempDaIdxs(1:length(x)))';
col = daConc(tempDaIdxs(1:length(x)))';  % This is the color, vary with x in this case.
surface([x;x],[y;y],[z;z],[col;col], 'facecol','no', 'edgecol','interp', 'linew',2); colormap(build_NOAA_colorgradient);




x = decimate(xpos, 3)'; y = decimate(ypos, 3)'; z = ((1:length(x))/10);
col = daConc(1:length(x))';  % This is the color, vary with x in this case.
figure; sf=surface([x;x],[y;y],[z;z],[col;col], 'facecol','no', 'edgecol','interp', 'linew',2); colormap(build_NOAA_colorgradient); colorbar;


% make a colored line with matlab
% figure;
% x = 0:.05:2*pi;
% y = sin(x);
% z = zeros(size(x));
% col = x;  % This is the color, vary with x in this case.
% surface([x;x],[y;y],[z;z],[col;col],...
%         'facecol','no',...
%         'edgecol','interp',...
%         'linew',2);


plotFft(ypos, 30, true);



tempNlxIdxs=min(find(((eventTimestamps-eventTimestamps(1))/(60e6))>startMinute)):max(find(((eventTimestamps-eventTimestamps(1))/(60e6))<endMinute));


eventTimestamps(pelletIdxs


figure;
[corr,lag]=xcorr(decimate(anyRewardDistance,3),daConc);
plot(lag/30,corr/(max(corr)-min(corr)));
plotFft(corr, 30, true);