ttPosition.h7.YYYYMMDD20180705  = {    'Str'   'Str'       'Str'      'x'         'Str'  'x'    'ctx'  'x'    'x'    'x'    'x'      'x'      'x'      'x'      'x'      'x'      'x'      'x'    'x'    'x'      'x'     'x'    'x'    'CA1'   'x'    'LV'       'LV'     'LV'      'x'           'LV'          'LV'    'LS'   };
ttPosition.h7.YYYYMMDD20180706  = {    'Str'   'x'         'Str'      'x'         'x'    'CA1'  'x'    'x'    'x'    'CA1'  'x'      'CA1'    'x'      'CA1'    'CA1'    'CA1'    'CA1'    'x'    'x'    'x'      'x'     'x'    'x'    'x'    'ctx'   'LV'       'LV'     'LV'      'x'           'LV'          'LV'    'x'    };
ttPosition.h7.YYYYMMDD20180711  = {    'Str'   'Str'       'Str'      'x'         'Str'  'CA1'  'x'    'x'    'ctx'  'CA1'  'x'      'x'      'ctx'    'CA1'    'CA1'    'x'      'x'      'x'    'CA1'  'x'      'x'     'x'    'x'    'CA1'  'ctx'   'LV'       'LV'     'LV'      'x'           'LV'          'LV'    'LS'   };
ttPosition.h7.YYYYMMDD20180712  = {    'Str'   'Str'       'Str'      'x'         'Str'  'CA1'  'x'    'ctx'  'ctx'  'x'    'x'      'x'      'ctx'    'x'      'CA1'    'x'      'x'      'x'    'x'    'x'      'x'     'x'    'x'    'x'    'ctx'   'LV'       'LS'     'LV'      'x'           'LV'          'LS'    'LS'   };
ttPosition.h7.YYYYMMDD20180713  = {    'Str'   'Str'       'Str'      'x'         'Str'  'CA1'  'x'    'x'    'x'    'CA1'  'CA1'    'x'      'x'      'x'      'x'      'x'      'x'      'CA1'  'x'    'x'      'x'     'x'    'x'    'x'    'cc'    'LV'       'LS'     'LV'      'x'           'LV'          'LV'    'LS'   };
ttPosition.h7.YYYYMMDD20180716  = {    'x'     'x'         'x'        'x'         'Str'  'x'    'x'    'x'    'x'    'CA1'  'CA1'    'CA1'    'ctx'    'CA1'    'x'      'x'      'CA1'    'x'    'x'    'x'      'x'     'x'    'x'    'x'    'cc'    'LV'       'LS'     'LV'      'x'           'LV'          'LS'    'LS'   };
ttPosition.h7.YYYYMMDD20180718  = {    'x'     'x'         'Str'      'x'         'Str'  'x'    'ctx'  'ctx'  'x'    'CA1'  'x'      'CA1'    'ctx'    'CA1'    'x'      'x'      'CA1'    'x'    'x'    'x'      'x'     'x'    'x'    'x'    'cc'    'LV'       'x'      'LS'      'x'           'LS'          'LS'    'LS'   };
ttPosition.h7.YYYYMMDD20180719  = {    'Str'   'Str'       'Str'      'x'         'Str'  'x'    'x'    'x'    'x'    'CA1'  'CA1'    'CA1'    'ctx'    'CA1'    'CA1'    'x'      'CA1'    'CA1'  'CA1'  'x'      'CA1'   'CA1'  'ctx'  'x'    'cc'    'LS'       'LS'     'LS'      'ctx'         'LS'          'LS'    'LS'   };
ttPosition.h7.YYYYMMDD20180720  = {    'Str'   'Str'       'x'        'Str'       'Str'  'x'    'x'    'x'    'x'    'CA1'  'CA1'    'CA1'    'ctx'    'CA1'    'CA1'    'x'      'CA1'    'x'    'CA1'  'x'      'CA1'   'CA1'  'x'    'x'    'cc'    'LS'       'x'      'LS'      'ctx'         'LS'          'LS'    'LS'   };
ttPosition.h7.YYYYMMDD20180723  = {    'Str'   'x'         'Str'      'Str'       'Str'  'x'    'ctx'  'x'    'x'    'CA1'  'CA1'    'CA1'    'ctx'    'CA1'    'CA1'    'x'      'CA1'    'x'    'x'    'x'      'CA1'   'CA1'  'ctx'  'x'    'cc'    'LS'       'LS'     'LS'      'ctx'         'LS'          'LS'    'LS'   };
ttPosition.h7.YYYYMMDD20180724  = {    'Str'   'x'         'Str'      'Str'       'Str'  'x'    'ctx'  'x'    'ctx'  'CA1'  'CA1'    'CA1'    'ctx'    'CA1'    'CA1'    'x'      'CA1'    'x'    'x'    'x'      'CA1'   'CA1'  'x'    'x'    'LS'    '3v'       '3v'     'x'       'x'           'x'           'LS'    'LS'   };
ttPosition.h7.YYYYMMDD20180725  = {    'Str'   'LS'        'Str'      'x'         'Str'  'CA1'  'x'    'x'    'ctx'  'CA1'  'CA1'    'CA1'    'ctx'    'CA1'    'CA1'    'x'      'CA1'    'x'    'x'    'x'      'CA1'   'CA1'  'ctx'  'CA1'  'LS'    '3v'       'Thal'   'x'       'x'           'LS'          'LS'    'LS'   };
ttPosition.h7.YYYYMMDD20180726  = {    'x'     'LS'        'Str'      'NAc'       'Str'  'x'    'x'    'ctx'  'ctx'  'CA1'  'CA1'    'CA1'    'ctx'    'CA1'    'CA1'    'CA1'    'CA1'    'x'    'CA1'  'x'      'CA1'   'CA1'  'x'    'CA1'  'LS'    '3v'       'Thal'   'LS'      'x'           'x'           'LS'    'LS'   };
ttPosition.h7.YYYYMMDD20180727  = {    'x'     'LS'        'Str'      'NAc'       'Str'  'CA1'  'ctx'  'ctx'  'ctx'  'CA1'  'CA1'    'CA1'    'ctx'    'CA1'    'CA1'    'CA1'    'CA1'    'x'    'x'    'x'      'x'     'x'    'x'    'CA1'  'LS'    '3v'       'Thal'   'LS'      'x'           'x'           'LS'    'LS'   };
ttPosition.h7.YYYYMMDD20180730  = {    'Str'   'LS'        'Str'      'NAc'       'Str'  'CA1'  'ctx'  'ctx'  'ctx'  'CA1'  'CA1'    'CA1'    'ctx'    'CA1'    'CA1'    'CA1'    'CA1'    'x'    'x'    'x'      'CA1'   'CA1'  'x'    'x'    'LS'    '3v'       'Thal'   'x'       'LS'          'x'           'LS'    'LS'   };
ttPosition.h7.YYYYMMDD20180801a = {    'BNST'  'LS'        'Str'      'NAc'       'Str'  'CA1'  'ctx'  'ctx'  'ctx'  'CA1'  'CA1'    'CA1'    'ctx'    'CA1'    'CA1'    'CA1'    'CA1'    'x'    'CA1'  'ctx'    'CA1'   'CA1'  'ctx'  'CA1'  'LS'    'Thal'     'Thal'   'LS'      'LS'          'LS'          'LS'    'LS'   };
ttPosition.h7.YYYYMMDD20180801b = {    'BNST'  'LS'        'Str'      'NAc'       'Str'  'CA1'  'ctx'  'ctx'  'ctx'  'x'    'CA1'    'CA1'    'ctx'    'CA1'    'CA1'    'CA1'    'CA1'    'x'    'CA1'  'ctx'    'CA1'   'CA1'  'ctx'  'CA1'  'LS'    'Thal'     'Thal'   'LS'      'LS'          'LS'          'x'     'LS'   };
ttPosition.h7.YYYYMMDD20180801c = {    'BNST'  'LS'        'Str'      'NAc'       'Str'  'CA1'  'ctx'  'ctx'  'ctx'  'CA1'  'CA1'    'CA1'    'ctx'    'CA1'    'CA1'    'CA1'    'CA1'    'x'    'CA1'  'ctx'    'CA1'   'CA1'  'ctx'  'CA1'  'LS'    'Thal'     'Thal'   'LS'      'LS'          'LS'          'LS'    'LS'   };
ttPosition.h7.YYYYMMDD20180802  = {    'BNST'  'LS'        'Str'      'NAc'       'Str'  'x'    'ctx'  'ctx'  'ctx'  'CA1'  'CA1'    'CA1'    'ctx'    'CA1'    'CA1'    'CA1'    'CA1'    'x'    'CA1'  'ctx'    'CA1'   'CA1'  'x'    'CA1'  'LS'    'Thal'     'Thal'   'LS'      'LS'          'x'           'LS'     'x'   };
ttPosition.h7.YYYYMMDD20180803a = {    'BNST'  'LS'        'Str'      'x'         'Str'  'CA1'  'x'    'ctx'  'x'    'CA1'  'CA1'    'CA1'    'ctx'    'CA1'    'CA1'    'x'      'CA1'    'x'    'CA1'  'ctx'    'CA1'   'CA1'  'x'    'CA1'  'LS'    'Thal'     'Thal'   'x'       'LS'          'x'           'SHy'    'SHy' };
ttPosition.h7.YYYYMMDD20180803b = {    'BNST'  'LS'        'Str'      'NAc'       'Str'  'x'    'ctx'  'ctx'  'x'    'CA1'  'CA1'    'CA1'    'ctx'    'CA1'    'CA1'    'CA1'    'CA1'    'x'    'x'    'ctx'    'CA1'   'CA1'  'x'    'CA1'  'LS'    'nReun'    'Thal'   'x'       'LS'          'x'           'SHy'    'SHy' };
ttPosition.h7.YYYYMMDD20180806  = {    'BNST'  'hypoThal'  'Str'      'NAc'       'Str'  'CA1'  'ctx'  'ctx'  'x'    'CA1'  'CA1'    'CA1'    'ctx'    'CA1'    'CA1'    'CA1'    'CA1'    'x'    'CA1'  'ctx'    'CA1'   'CA1'  'x'    'CA1'  'LS'    'nReun'    'x'      'LS'      'LS'          'x'           'SHy'    'SHy' };
ttPosition.h7.YYYYMMDD20180807  = {    'BNST'  'hypoThal'  'Str'      'NAc'       'Str'  'CA1'  'ctx'  'ctx'  'x'    'CA1'  'CA1'    'CA1'    'ctx'    'CA1'    'CA1'    'CA1'    'CA1'    'x'    'x'    'ctx'    'CA1'   'CA1'  'x'    'x'    'LS'    'nReun'    'AM'     'x'       'LS'          'x'           'x'      'SHy' };
ttPosition.h7.YYYYMMDD20180808  = {    'BNST'  'hypoThal'  'x'        'x'         'Str'  'CA1'  'ctx'  'ctx'  'Str'  'CA1'  'CA1'    'CA1'    'ctx'    'CA1'    'CA1'    'CA1'    'CA1'    'x'    'x'    'ctx'    'CA1'   'CA1'  'x'    'x'    'LS'    'nReun'    'AM'     'x'       'LS'          'hypoThal'    'SHy'    'SHy' };
ttPosition.h7.YYYYMMDD20180809  = {    'BNST'  'x'         'NAc'      'str_pal'   'Str'  'CA1'  'ctx'  'ctx'  'Str'  'CA1'  'CA1'    'CA1'    'ctx'    'CA1'    'CA1'    'CA1'    'CA1'    'x'    'x'    'ctx'    'x'     'x'    'x'    'CA1'  'LS'    'nReun'    'AM'     'x'       'x'           'x'           'SHy'    'SHy' };
ttPosition.h7.YYYYMMDD20180810  = {    'BNST'  'LPO'       'NAc'      'str_pal'   'Str'  'CA1'  'ctx'  'x'    'Str'  'CA1'  'CA1'    'CA1'    'ctx'    'CA1'    'CA1'    'CA1'    'CA1'    'x'    'x'    'ctx'    'CA1'   'CA1'  'x'    'x'    'LS'    'nReun'    'x'      'x'       'hypoThal'    'hypoThal'    'SHy'    'SHy' };
ttPosition.h7.YYYYMMDD20180813  = {    'BNST'  'LPO'       'NAc'      'str_pal'   'Str'  'x'    'ctx'  'x'    'Str'  'x'    'CA1'    'CA1'    'ctx'    'CA1'    'CA1'    'CA1'    'CA1'    'x'    'x'    'ctx'    'CA1'   'CA1'  'x'    'x'    'vhc'   'nReun'    'nReun'  'LS'      'hypoThal'    'hypoThal'    'SHy'    'SHy' };
ttPosition.h7.YYYYMMDD20180814  = {    'BNST'  'x'         'NAc'      'x'         'Str'  'x'    'x'    'x'    'Str'  'x'    'CA1'    'CA1'    'ctx'    'CA1'    'CA1'    'CA1'    'CA1'    'x'    'x'    'x'      'CA1'   'CA1'  'x'    'CA1'  'vhc'   'nReun'    'x'      'x'       'x'           'hypoThal'    'SHy'    'SHy' };
ttPosition.h7.YYYYMMDD20180815  = {    'BNST'  'SIB'       'NAc'      'str_pal'   'Str'  'CA1'  'ctx'  'x'    'Str'  'x'    'CA1'    'CA1'    'ctx'    'CA1'    'CA1'    'x'      'CA1'    'x'    'x'    'x'      'CA1'   'CA1'  'x'    'CA1'  'vhc'   'nReun'    'x'      'x'       'x'           'hypoThal'    'x'      'MPA' };
ttPosition.h7.YYYYMMDD20180822  = {    'BNST'  'SIB'       'str_pal'  'str_pal'   'Str'  'CA1'  'ctx'  'ctx'  'Str'  'CA1'  'CA1'    'CA1'    'ctx'    'CA1'    'CA1'    'CA1'    'CA1'    'x'    'CA1'  'ctx'    'CA1'   'CA1'  'ctx'  'CA1'  'vhc'   'nReun'    'MPO'    'LS'      'hypoThal'    'hypoThal'    'MPA'    'MPA' };
ttPosition.h7.YYYYMMDD20180827  = {    'x'     'x'         'x'        'x'         'x'    'x'    'x'    'x'    'x'    'x'    'x'      'x'      'x'      'x'      'x'      'x'      'x'      'x'    'x'    'x'      'x'     'x'    'x'    'x'    '3v'    '3v'       'x'      'fornix'  'x'           'x'           'x'      'x'   };
ttPosition.h7.YYYYMMDD20180828  = {    'LPO'   'HDB'       'str_pal'  'str_pal'   'x'    'x'    'ctx'  'ctx'  'Str'  'CA1'  'CA1'    'CA1'    'ctx'    'CA1'    'CA1'    'CA1'    'CA1'    'x'    'x'    'x'      'CA1'   'CA1'  'ctx'  'CA1'  'PVA'   '3v'       'x'      'LS'      'hypoThal'    'hypoThal'    'MPA'    'MPA' };
ttPosition.h7.YYYYMMDD20180831  = {    'x'     'x'         'x'        'x'         'x'    'x'    'x'    'x'    'x'    'x'    'CA1'    'CA1'    'ctx'    'CA1'    'CA1'    'CA1'    'CA1'    'x'    'x'    'x'      'x'     'x'    'x'    'CA1'  'PVA'   '3v'       'x'      'fornix'  'x'           'x'           'MPA'    'MPA' };
ttPosition.h7.YYYYMMDD20180904  = {    'LPO'   'HDB'       'str_pal'  'str_pal'   'x'    'CA1'  'ctx'  'ctx'  'Str'  'CA1'  'CA1'    'CA1'    'ctx'    'CA1'    'CA1'    'x'      'x'      'x'    'x'    'ctx'    'x'     'x'    'ctx'  'CA1'  'PVA'   'hypoThal' 'MPO'    'LS'      'hypoThal'    'hypoThal'    'MPA'    'MPA' };
ttPosition.h7.YYYYMMDD20180905  = {    'x'     'x'         'x'        'x'         'x'    'x'    'x'    'x'    'Str'  'CA1'  'CA1'    'CA1'    'ctx'    'CA1'    'CA1'    'CA1'    'CA1'    'x'    'x'    'ctx'    'x'     'x'    'x'    'CA1'  'PVA'   'x'        'x'      'x'       'x'           'x'           'x'      'x'   };


ttPosition.h5.YYYYMMDD20180425  = {    'x'     'x'         'Str'      'Str'      'Str'    'Str'    'x'    'x'      'x'    'x'     'x'    'x'    'x'      'CA1'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'CA1'    'x'    'x'    'x'    'x'    'x'    'x'     'x'    'x'    'x'    'x'   };
ttPosition.h5.YYYYMMDD20180427  = {    'x'     'x'         'Str'      'Str'      'Str'    'Str'    'x'    'ctx'    'ctx'  'CA1'   'x'    'x'    'x'      'CA1'    'CA1'  'x'    'x'    'x'    'CA1'  'CA1'  'x'    'CA1'    'x'    'CA1'  'ctx'  'x'    'x'    'x'     'x'    'ctx'  'x'    'Str' };
ttPosition.h5.YYYYMMDD20180501  = {    'x'     'x'         'Str'      'Str'      'Str'    'Str'    'x'    'x'      'x'    'x'     'x'    'x'    'x'      'x'      'x'    'x'    'x'    'x'    'x'    'x'    'CA1'  'x'      'x'    'x'    'x'    'x'    'x'    'x'     'x'    'x'    'x'    'x'   };
ttPosition.h5.YYYYMMDD20180502  = {    'x'     'x'         'Str'      'Str'      'Str'    'Str'    'x'    'ctx'    'x'    'CA1'   'x'    'CA1'  'CA3'    'CA1'    'CA1'  'CA1'  'x'    'x'    'x'    'CA1'  'x'    'x'      'x'    'x'    'x'    'ctx'  'LS'   'x'     'Str'  'x'    'x'    'Str' };
ttPosition.h5.YYYYMMDD20180503  = {    'x'     'x'         'Str'      'Str'      'Str'    'Str'    'x'    'ctx'    'x'    'x'     'x'    'CA1'  'CA3'    'CA1'    'CA1'  'CA1'  'CA1'  'x'    'x'    'CA1'  'x'    'x'      'x'    'x'    'x'    'x'    'LS'   'x'     'x'    'x'    'x'    'x'   };
ttPosition.h5.YYYYMMDD20180507  = {    'x'     'x'         'Str'      'Str'      'Str'    'Str'    'x'    'ctx'    'x'    'x'     'x'    'x'    'CA3'    'CA1'    'CA1'  'x'    'CA1'  'x'    'CA1'  'CA1'  'CA1'  'x'      'x'    'CA1'  'ctx'  'x'    'x'    'x'     'x'    'x'    'x'    'x'   };
ttPosition.h5.YYYYMMDD20180508  = {    'x'     'x'         'Str'      'Str'      'Str'    'Str'    'x'    'ctx'    'x'    'x'     'x'    'CA1'  'CA3'    'CA1'    'CA1'  'CA1'  'CA1'  'x'    'CA1'  'CA1'  'CA1'  'x'      'x'    'x'    'x'    'x'    'LS'   'x'     'x'    'x'    'x'    'x'   };
ttPosition.h5.YYYYMMDD20180509  = {    'x'     'x'         'Str'      'Str'      'Str'    'Str'    'x'    'ctx'    'x'    'x'     'x'    'CA1'  'CA3'    'x'      'x'    'CA1'  'CA1'  'x'    'x'    'CA1'  'CA1'  'x'      'x'    'x'    'ctx'  'ctx'  'LS'   'x'     'x'    'x'    'Str'  'x'   };
ttPosition.h5.YYYYMMDD20180511  = {    'LS'    'LS'        'Str'      'Str'      'Str'    'Str'    'x'    'ctx'    'ctx'  'x'     'x'    'CA1'  'CA3'    'x'      'x'    'CA1'  'CA1'  'x'    'CA1'  'x'    'CA1'  'x'      'x'    'x'    'x'    'x'    'LS'   'LS'    'x'    'x'    'Str'  'x'   };
ttPosition.h5.YYYYMMDD20180514  = {    'LS'    'x'         'Str'      'Str'      'Str'    'Str'    'x'    'ctx'    'x'    'x'     'x'    'CA1'  'CA3'    'CA1'    'x'    'CA1'  'CA1'  'x'    'x'    'CA1'  'CA1'  'CA1'    'x'    'x'    'x'    'x'    'LS'   'LS'    'LS'   'Str'  'LS'   'LS'  };
ttPosition.h5.YYYYMMDD20180515  = {    'LS'    'LS'        'Str'      'Str'      'Str'    'Str'    'x'    'ctx'    'x'    'x'     'x'    'CA1'  'CA3'    'x'      'x'    'CA1'  'CA1'  'x'    'x'    'CA1'  'CA1'  'x'      'x'    'x'    'ctx'  'x'    'LS'   'LS'    'LS'   'x'    'LS'   'LS'  };
ttPosition.h5.YYYYMMDD20180516  = {    'LS'    'x'         'Str'      'Str'      'Str'    'Str'    'x'    'ctx'    'x'    'CA1'   'x'    'CA1'  'CA3'    'x'      'x'    'x'    'x'    'x'    'x'    'CA1'  'CA1'  'x'      'x'    'CA1'  'ctx'  'x'    'LS'   'LS'    'LS'   'x'    'LS'   'LS'  };
ttPosition.h5.YYYYMMDD20180518  = {    'LS'    'x'         'Str'      'Str'      'Str'    'Str'    'x'    'ctx'    'x'    'x'     'x'    'x'    'CA3'    'CA1'    'x'    'x'    'CA1'  'x'    'x'    'CA1'  'CA1'  'CA1'    'x'    'CA1'  'ctx'  'x'    'LS'   'LS'    'LS'   'x'    'LS'   'LS'  };
ttPosition.h5.YYYYMMDD20180608  = {    'LS'    'LS'        'Str'      'Str'      'Str'    'Str'    'x'    'ctx'    'ctx'  'CA1'   'x'    'CA1'  'CA3'    'x'      'x'    'CA1'  'x'    'x'    'x'    'x'    'x'    'x'      'x'    'x'    'ctx'  'ctx'  'LS'   'x'     'LS'   'x'    'x'    'x'   };
ttPosition.h5.YYYYMMDD20180611  = {    'LS'    'x'         'Str'      'Str'      'Str'    'Str'    'x'    'x'      'ctx'  'CA1'   'x'    'CA1'  'CA3'    'x'      'x'    'CA1'  'x'    'x'    'x'    'x'    'x'    'x'      'x'    'x'    'ctx'  'x'    'LS'   'LS'    'x'    'x'    'x'    'LS'  };
ttPosition.h5.YYYYMMDD20180612  = {    'LS'    'x'         'Str'      'Str'      'Str'    'Str'    'x'    'ctx'    'x'    'CA1'   'x'    'CA1'  'CA3'    'x'      'x'    'CA1'  'x'    'x'    'x'    'x'    'x'    'CA1'    'x'    'x'    'ctx'  'x'    'x'    'x'     'LS'   'x'    'LS'   'x'   };
ttPosition.h5.YYYYMMDD20180613  = {    'LS'    'x'         'Str'      'Str'      'Str'    'Str'    'x'    'ctx'    'x'    'CA1'   'x'    'CA1'  'CA3'    'x'      'CA1'  'CA1'  'CA1'  'CA1'  'CA1'  'x'    'CA1'  'CA1'    'x'    'CA1'  'ctx'  'ctx'  'LS'   'LS'    'LS'   'x'    'LS'   'LS'  };
ttPosition.h5.YYYYMMDD20180614  = {    'LS'    'x'         'NAc'      'Str'      'Str'    'Str'    'x'    'ctx'    'ctx'  'CA1'   'x'    'CA1'  'CA3'    'x'      'x'    'CA1'  'x'    'x'    'x'    'x'    'x'    'x'      'x'    'x'    'ctx'  'ctx'  'LS'   'LS'    'LS'   'Str'  'LS'   'LS'  };
ttPosition.h5.YYYYMMDD20180615  = {    'LS'    'x'         'NAc'      'NAc'      'NAc'    'Str'    'x'    'ctx'    'x'    'CA1'   'x'    'x'    'CA3'    'x'      'x'    'CA1'  'x'    'x'    'x'    'x'    'x'    'x'      'x'    'x'    'x'    'x'    'LS'   'LS'    'LS'   'x'    'x'    'LS'  }; 
  

ttPosition.h1.YYYYMMDD20180809  = {    'NAc'   'x'         'Str'      'HF'      'ctx'    'CA3'    'x'    'x'      'CA1'  'PAG'    'x'    'VTA'    'x'      'retF'    'VTA'    'x'    'CA1'    'x'    'x'    'x'    'x'      'CA3'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.h1.YYYYMMDD20180810  = {    'NAc'   'x'         'Str'      'HF'      'ctx'    'CA3'    'x'    'x'      'CA1'  'PAG'    'x'    'VTA'    'VTA'    'retF'    'VTA'    'x'    'CA1'    'x'    'x'    'x'    'x'      'CA3'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.h1.YYYYMMDD20180813  = {    'NAc'   'x'         'Str'      'HF'      'ctx'    'CA3'    'x'    'x'      'CA1'  'PAG'    'x'    'VTA'    'x'      'retF'    'VTA'    'x'    'CA1'    'x'    'x'    'x'    'x'      'CA3'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.h1.YYYYMMDD20180814  = {    'NAc'   'x'         'Str'      'HF'      'ctx'    'CA3'    'x'    'x'      'CA1'  'x'      'x'    'VTA'    'VTA'    'x'       'VTA'    'x'    'CA1'    'x'    'x'    'x'    'x'      'CA3'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.h1.YYYYMMDD20180815  = {    'NAc'   'x'         'Str'      'HF'      'ctx'    'CA3'    'x'    'x'      'CA1'  'PAG'    'x'    'VTA'    'VTA'    'retF'    'VTA'    'x'    'CA1'    'x'    'x'    'x'    'x'      'CA3'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.h1.YYYYMMDD20180817  = {    'NAc'   'x'         'Str'      'x'       'x'      'x'      'x'    'x'      'x'    'PAG'    'x'    'VTA'    'VTA'    'retF'    'VTA'    'x'    'x'      'x'    'x'    'x'    'x'      'CA3'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.h1.YYYYMMDD20180822  = {    'NAc'   'x'         'Str'      'HF'      'x'      'CA3'    'x'    'x'      'HF'   'PAG'    'x'    'VTA'    'VTA'    'retF'    'VTA'    'x'    'CA1'    'x'    'x'    'x'    'ctx'    'CA3'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.h1.YYYYMMDD20180823  = {    'NAc'   'x'         'Str'      'HF'      'CA3'    'CA3'    'x'    'CA1'    'HF'   'PAG'    'x'    'VTA'    'VTA'    'retF'    'VTA'    'x'    'x'      'x'    'x'    'x'    'ctx'    'CA3'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.h1.YYYYMMDD20180824  = {    'NAc'   'x'         'Str'      'HF'      'CA3'    'CA3'    'x'    'CA1'    'HF'   'PAG'    'x'    'VTA'    'VTA'    'retF'    'VTA'    'x'    'CA1'    'x'    'x'    'x'    'ctx'    'CA3'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.h1.YYYYMMDD20180827a = {    'NAc'   'x'         'Str'      'HF'      'CA3'    'CA3'    'x'    'CA1'    'HF'   'PAG'    'x'    'VTA'    'VTA'    'retF'    'VTA'    'x'    'CA1'    'x'    'x'    'x'    'ctx'    'CA3'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.h1.YYYYMMDD20180827b = {    'NAc'   'x'         'Str'      'HF'      'CA3'    'CA3'    'x'    'CA1'    'HF'   'PAG'    'x'    'VTA'    'VTA'    'retF'    'VTA'    'x'    'CA1'    'x'    'x'    'x'    'ctx'    'CA3'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.h1.YYYYMMDD20180828  = {    'NAc'   'x'         'Str'      'HF'      'CA3'    'CA3'    'x'    'HF'     'HF'   'PAG'    'x'    'VTA'    'VTA'    'PAG'     'VTA'    'x'    'CA1'    'x'    'x'    'x'    'ctx'    'CA3'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.h1.YYYYMMDD20180829  = {    'NAc'   'x'         'Str'      'HF'      'CA3'    'CA3'    'x'    'HF'     'HF'   'PAG'    'x'    'x'      'x'      'PAG'     'VTA'    'x'    'CA1'    'x'    'x'    'x'    'ctx'    'CA3'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.h1.YYYYMMDD20180830  = {    'NAc'   'x'         'Str'      'x'       'x'      'x'      'x'    'HF'     'DG'   'PAG'    'x'    'x'      'VTA'    'PAG'     'VTA'    'x'    'x'      'x'    'x'    'x'    'x'      'CA3'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.h1.YYYYMMDD20180831  = {    'NAc'   'x'         'Str'      'HF'      'x'      'CA3'    'x'    'HF'     'DG'   'PAG'    'x'    'x'      'VTA'    'x'       'VTA'    'x'    'CA1'    'x'    'x'    'x'    'ctx'    'CA3'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.h1.YYYYMMDD20180904  = {    'NAc'   'x'         'Str'      'HF'      'CA3'    'CA3'    'x'    'HF'     'DG'   'PAG'    'x'    'x'      'VTA'    'x'       'VTA'    'x'    'CA1'    'x'    'x'    'x'    'ctx'    'CA3'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.h1.YYYYMMDD20180905  = {    'NAc'   'x'         'Str'      'x'       'CA3'    'x'      'x'    'HF'     'x'    'PAG'    'x'    'x'      'VTA'    'PAG'     'VTA'    'x'    'CA1'    'x'    'x'    'x'    'ctx'    'CA3'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.h1.YYYYMMDD20180906  = {    'NAc'   'x'         'Str'      'HF'      'CA3'    'CA3'    'x'    'CA3'    'x'    'PAG'    'x'    'x'      'VTA'    'x'       'VTA'    'x'    'CA1'    'x'    'x'    'x'    'ctx'    'CA3'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.h1.YYYYMMDD20180907  = {    'NAc'   'x'         'Str'      'HF'      'CA3'    'x'      'x'    'CA3'    'CA3'  'PAG'    'x'    'x'      'VTA'    'x'       'VTA'    'x'    'CA1'    'x'    'x'    'x'    'ctx'    'CA3'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.h1.YYYYMMDD20180908  = {    'NAc'   'x'         'Str'      'HF'      'CA3'    'CA3'    'x'    'CA3'    'CA3'  'PAG'    'x'    'x'      'VTA'    'x'       'VTA'    'x'    'CA1'    'x'    'x'    'x'    'ctx'    'CA3'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.h1.YYYYMMDD20180909  = {    'NAc'   'x'         'x'        'HF'      'CA3'    'CA3'    'x'    'CA3'    'x'    'PAG'    'x'    'x'      'VTA'    'x'       'VTA'    'x'    'CA1'    'x'    'x'    'x'    'ctx'    'CA3'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.h1.YYYYMMDD20180914  = {    'NAc'   'x'         'Str'      'HF'      'CA3'    'CA3'    'x'    'CA3'    'CA3'  'PAG'    'x'    'VTA'    'VTA'    'x'       'VTA'    'x'    'CA1'    'x'    'x'    'x'    'ctx'    'CA3'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
 

ttPosition.da10.YYYYMMDD20170911  = {      'x'      'x'    'x'    'x'     'x'    'x'    'x'    'x'    'x'    'x'    'x'       'x'    'x'    'HF'    'x'    'x'     'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.da10.YYYYMMDD20170912  = {      'x'      'x'    'x'    'x'     'x'    'x'    'x'    'x'    'x'    'x'    'x'       'x'    'x'     'x'    'x'    'x'     'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.da10.YYYYMMDD20170913  = {      'x'      'x'    'x'    'x'     'x'    'x'    'x'    'x'    'x'    'x'    'x'       'x'    'x'     'x'    'x'    'x'     'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.da10.YYYYMMDD20170914  = {      'x'      'x'    'x'    'x'     'x'    'x'    'x'    'x'    'x'    'x'    'x'    'retF'    'x'    'HF'    'x'    'x'     'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.da10.YYYYMMDD20170915  = {      'x'    'Str'    'x'    'x'     'x'    'x'    'x'    'x'    'x'    'x'    'x'    'retF'    'x'    'HF'    'x'    'x'     'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.da10.YYYYMMDD20170918  = {    'Str'    'Str'    'x'    'x'    'HF'    'x'    'x'    'x'    'x'    'x'    'x'    'retF'    'x'    'HF'    'x'    'x'     'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.da10.YYYYMMDD20170919  = {      'x'    'Str'    'x'    'x'     'x'    'x'    'x'    'x'    'x'    'x'    'x'    'retF'    'x'    'HF'    'x'    'x'     'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.da10.YYYYMMDD20170920  = {      'x'    'Str'    'x'    'x'     'x'    'x'    'x'    'x'    'x'    'x'    'x'    'retF'    'x'    'HF'    'x'    'x'    'HF'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.da10.YYYYMMDD20170922  = {      'x'    'Str'    'x'    'x'     'x'    'x'    'x'    'x'    'x'    'x'    'x'    'retF'    'x'    'HF'    'x'    'x'    'HF'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.da10.YYYYMMDD20170925  = {      'x'    'Str'    'x'    'x'     'x'    'x'    'x'    'x'    'x'    'x'    'x'    'retF'    'x'    'HF'    'x'    'x'    'HF'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };


ttPosition.da5.YYYYMMDD20160822  = {   'x'     'x'       'x'       'x'      'x'      'x'     'x'     'x'    'x'     'x'     'x'     'x'    'x'      'x'      'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.da5.YYYYMMDD20160823  = {   'x'     'x'       'x'       'x'      'x'      'x'     'x'     'x'    'x'     'x'     'x'     'x'    'x'      'x'      'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.da5.YYYYMMDD20160824  = {   'x'     'x'    'retF'     'VTA'      'x'    'ctx'     'x'     'x'    'x'     'x'     'x'     'x'    'x'      'x'      'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.da5.YYYYMMDD20160825  = {   'x'     'x'       'x'       'x'      'x'      'x'     'x'     'x'    'x'     'x'     'x'     'x'    'x'      'x'      'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.da5.YYYYMMDD20160826  = {   'x'     'x'       'x'       'x'      'x'      'x'     'x'     'x'    'x'     'x'     'x'     'x'    'x'      'x'      'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.da5.YYYYMMDD20160827  = {   'x'    'HF'       'x'       'x'    'ctx'      'x'    'HF'    'HF'    'x'    'HF'     'x'     'x'    'x'    'Str'    'Str'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.da5.YYYYMMDD20160828  = {   'x'     'x'       'x'       'x'      'x'      'x'     'x'     'x'    'x'     'x'     'x'     'x'    'x'      'x'      'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.da5.YYYYMMDD20160829  = {  'HF'    'HF'       'x'       'x'    'ctx'      'x'    'HF'    'HF'    'x'    'HF'     'x'     'x'    'x'    'Str'    'Str'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.da5.YYYYMMDD20160830  = {  'HF'     'x'       'x'       'x'    'ctx'      'x'    'HF'    'HF'    'x'    'HF'     'x'     'x'    'x'    'Str'    'Str'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.da5.YYYYMMDD20160831  = {   'x'    'HF'       'x'       'x'    'ctx'      'x'    'HF'    'HF'    'x'    'HF'     'x'     'x'    'x'    'Str'    'Str'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.da5.YYYYMMDD20160901  = {  'HF'    'HF'       'x'       'x'    'ctx'      'x'    'HF'    'HF'    'x'    'HF'     'x'     'x'    'x'    'Str'    'Str'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.da5.YYYYMMDD20160902  = {  'HF'     'x'       'x'       'x'    'ctx'      'x'    'HF'    'HF'    'x'    'HF'     'x'     'x'    'x'    'Str'    'Str'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.da5.YYYYMMDD20160906  = {  'HF'    'HF'       'x'     'VTA'    'ctx'      'x'    'HF'    'HF'    'x'    'HF'     'x'    'HF'    'x'    'Str'    'Str'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.da5.YYYYMMDD20160907  = {  'HF'    'HF'    'retF'     'VTA'    'ctx'      'x'    'HF'    'HF'    'x'    'HF'     'x'     'x'    'x'    'Str'    'Str'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };
ttPosition.da5.YYYYMMDD20160908  = {  'HF'     'x'    'retF'     'VTA'    'ctx'    'ctx'    'HF'    'HF'    'x'    'HF'    'HF'    'HF'    'x'    'Str'    'Str'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x'    'x' };


bolt.h1 = {    2    5    6    7    8     9    10    11    13    16    18    19    22    15    17    21    23    25    26    27    28    29    31    34     0     0     0     0     0     0     0     0 };
bolt.h7 = {    1    2    3    4    5    26     7     8     9    10    11    12    13    14    15    16    17    18    19    20    21    22    23    24    28    29    30    31    32    33    34    35 };
bolt.h5 = {    1    2    3    4    5     6     7     8     9    10    11    12    13    14    15    16    17    19    20    21    22    23    24    25    27    28    29    30    31    32    34    35 };





%~isempty( strfind( ( ttPosition.(rat).(strcat('YYYYMMDD',(strrep(date,'-','')))){ttNum} ) , 'LS' )







%% OLD VERSION 2


% ttPosition.h5.YYYYMMDD20180425 = {     '?',     '?',     '?',     '?',    'Str',    'Str',    '?',      '?',      '?',     '?',    '?',     '?',     '?',    'HF',     '?',     '?',     '?',     '?',     '?',     '?',     '?',    'HF',    '?',     '?',     '?',      '?',      '?',     '?',     '?',     '?',     '?',     '?' };
% ttPosition.h5.YYYYMMDD20180427 = {     '?',     '?',   'Str',   'Str',    'Str',    'Str',    '?',    'ctx',    'ctx',    'HF',    '?',     '?',     '?',    'HF',    'HF',     '?',     '?',     '?',    'HF',    'HF',     '?',    'HF',    '?',    'HF',   'ctx',      '?',      '?',     '?',     '?',   'ctx',     '?',   'Str' };
% ttPosition.h5.YYYYMMDD20180501 = {     '?',     '?',     '?',   'Str',    'Str',    'Str',    '?',      '?',      '?',     '?',    '?',     '?',     '?',     '?',     '?',     '?',     '?',     '?',     '?',     '?',    'HF',     '?',    '?',     '?',     '?',      '?',      '?',     '?',     '?',     '?',     '?',     '?' };
% ttPosition.h5.YYYYMMDD20180502 = {     '?',     '?',     '?',   'Str',    'Str',    'Str',    '?',    'ctx',      '?',    'HF',    '?',    'HF',    'HF',    'HF',    'HF',    'HF',     '?',     '?',     '?',    'HF',     '?',     '?',    '?',     '?',     '?',    'ctx',    'Str',     '?',   'Str',     '?',     '?',   'Str' };
% ttPosition.h5.YYYYMMDD20180503 = {     '?',     '?',     '?',     '?',    'Str',    'Str',    '?',    'ctx',      '?',     '?',    '?',    'HF',    'HF',    'HF',    'HF',    'HF',    'HF',     '?',     '?',    'HF',     '?',     '?',    '?',     '?',     '?',      '?',    'Str',     '?',     '?',     '?',     '?',     '?' };
% ttPosition.h5.YYYYMMDD20180507 = {     '?',     '?',     '?',   'Str',    'Str',    'Str',    '?',    'ctx',      '?',     '?',    '?',     '?',    'HF',    'HF',    'HF',     '?',    'HF',     '?',    'HF',    'HF',    'HF',     '?',    '?',    'HF',   'ctx',      '?',      '?',     '?',     '?',     '?',     '?',     '?' };
% ttPosition.h5.YYYYMMDD20180508 = {     '?',     '?',     '?',     '?',    'Str',    'Str',    '?',    'ctx',      '?',     '?',    '?',    'HF',    'HF',    'HF',    'HF',    'HF',    'HF',     '?',    'HF',    'HF',    'HF',     '?',    '?',     '?',     '?',      '?',    'Str',     '?',     '?',     '?',     '?',     '?' };
% ttPosition.h5.YYYYMMDD20180509 = {     '?',     '?',     '?',   'Str',    'Str',    'Str',    '?',    'ctx',      '?',     '?',    '?',    'HF',    'HF',     '?',     '?',    'HF',    'HF',     '?',     '?',    'HF',    'HF',     '?',    '?',     '?',   'ctx',    'ctx',    'Str',     '?',     '?',     '?',   'Str',     '?' };
% ttPosition.h5.YYYYMMDD20180511 = {    'LS',    'LS',     '?',   'Str',    'Str',    'Str',    '?',    'ctx',    'ctx',     '?',    '?',    'HF',    'HF',     '?',     '?',    'HF',    'HF',     '?',    'HF',     '?',    'HF',     '?',    '?',     '?',     '?',      '?',    'Str',   'Str',     '?',     '?',   'Str',     '?' };
% ttPosition.h5.YYYYMMDD20180514 = {     '?',     '?',     '?',    'LS',    'Str',    'Str',    '?',    'ctx',      '?',     '?',    '?',    'HF',    'HF',    'HF',     '?',    'HF',    'HF',     '?',     '?',    'HF',    'HF',    'HF',    '?',     '?',     '?',      '?',     'LS',    'LS',    'LS',   'Str',    'LS',    'LS' };
% ttPosition.h5.YYYYMMDD20180515 = {    'LS',    'LS',     '?',    'LS',     'LS',    'Str',    '?',    'ctx',      '?',     '?',    '?',    'HF',    'HF',     '?',     '?',    'HF',    'HF',     '?',     '?',    'HF',    'HF',     '?',    '?',     '?',   'ctx',      '?',     'LS',    'LS',    'LS',     '?',    'LS',    'LS' };
% ttPosition.h5.YYYYMMDD20180516 = {     '?',     '?',     '?',     '?',     'LS',    'Str',    '?',    'ctx',      '?',    'HF',    '?',    'HF',    'HF',     '?',     '?',     '?',     '?',     '?',     '?',    'HF',    'HF',     '?',    '?',    'HF',   'ctx',      '?',     'LS',    'LS',    'LS',     '?',    'LS',    'LS' };
% ttPosition.h5.YYYYMMDD20180518 = {    'LS',     '?',     '?',     '?',     'LS',     'LS',    '?',    'ctx',      '?',     '?',    '?',     '?',    'HF',    'HF',     '?',     '?',    'HF',     '?',     '?',    'HF',    'HF',    'HF',    '?',    'HF',   'ctx',      '?',     'LS',    'LS',    'LS',     '?',    'LS',    'LS' };
% ttPosition.h5.YYYYMMDD20180608 = {     '?',    'LS',     '?',     '?',     'LS',     'LS',    '?',    'ctx',    'ctx',    'HF',    '?',    'HF',    'HF',     '?',     '?',    'HF',     '?',     '?',     '?',     '?',     '?',     '?',    '?',     '?',   'ctx',    'ctx',     'LS',     '?',    'LS',     '?',     '?',     '?' };
% ttPosition.h5.YYYYMMDD20180611 = {    'LS',     '?',     '?',    'LS',     'LS',     'LS',    '?',      '?',    'ctx',    'HF',    '?',    'HF',    'HF',     '?',     '?',    'HF',     '?',     '?',     '?',     '?',     '?',     '?',    '?',     '?',   'ctx',      '?',     'LS',    'LS',     '?',     '?',     '?',    'LS' };
% ttPosition.h5.YYYYMMDD20180612 = {     '?',     '?',     '?',     '?',     'LS',     'LS',    '?',    'ctx',      '?',    'HF',    '?',    'HF',    'HF',     '?',     '?',    'HF',     '?',     '?',     '?',     '?',     '?',    'HF',    '?',     '?',   'ctx',      '?',      '?',     '?',    'LS',     '?',    'LS',     '?' };
% ttPosition.h5.YYYYMMDD20180613 = {    'LS',     '?',   'Str',     '?',     'LS',     'LS',    '?',    'ctx',      '?',    'HF',    '?',    'HF',    'HF',     '?',    'HF',    'HF',    'HF',    'HF',    'HF',     '?',    'HF',    'HF',    '?',    'HF',   'ctx',    'ctx',     'LS',    'LS',    'LS',     '?',    'LS',    'LS' };
% ttPosition.h5.YYYYMMDD20180614 = {    'LS',     '?',     '?',     '?',     'LS',     'LS',    '?',    'ctx',    'ctx',    'HF',    '?',    'HF',    'HF',     '?',     '?',    'HF',     '?',     '?',     '?',     '?',     '?',     '?',    '?',     '?',   'ctx',    'ctx',     'LS',    'LS',    'LS',   'Str',    'LS',    'LS' };
% ttPosition.h5.YYYYMMDD20180615 = {    'LS',     '?',     '?',     '?',     'LS',     'LS',    '?',    'ctx',      '?',    'HF',    '?',     '?',    'HF',     '?',     '?',    'HF',     '?',     '?',     '?',     '?',     '?',     '?',    '?',     '?',     '?',      '?',     'LS',    'LS',    'LS',     '?',     '?',    'LS' };
%  
% 
% ttPosition.h7.YYYYMMDD20180705  = {     'Str',    'Str',     'Str',      '?',    'Str',     '?',    'ctx',      '?',      '?',     '?',     '?',     '?',      '?',     '?',     '?',     '?',     '?',    '?',    '?',      '?',     '?',     '?',    '?',    'HF',      '?',        '?',      '?',    '?',      '?',      '?',     '?',    'LS' };
% ttPosition.h7.YYYYMMDD20180706  = {     'Str',      '?',     'Str',      '?',    'Str',    'HF',      '?',      '?',      '?',    'HF',     '?',    'HF',      '?',    'HF',    'HF',    'HF',    'HF',    '?',    '?',      '?',     '?',     '?',    '?',     '?',    'ctx',        '?',      '?',    '?',      '?',      '?',     '?',     '?' };
% ttPosition.h7.YYYYMMDD20180711  = {     'Str',    'Str',     'Str',      '?',    'Str',    'HF',      '?',      '?',    'Str',    'HF',     '?',     '?',    'ctx',    'HF',    'HF',     '?',     '?',    '?',   'HF',      '?',     '?',     '?',    '?',    'HF',    'ctx',        '?',      '?',    '?',      '?',      '?',     '?',    'LS' };
% ttPosition.h7.YYYYMMDD20180712  = {     'Str',    'Str',     'Str',      '?',    'Str',    'HF',      '?',    'ctx',    'Str',     '?',     '?',     '?',    'ctx',     '?',    'HF',     '?',     '?',    '?',    '?',      '?',     '?',     '?',    '?',     '?',    'ctx',       'LV',     'LS',    '?',      '?',      '?',    'LS',    'LS' };
% ttPosition.h7.YYYYMMDD20180713  = {     'Str',    'Str',     'Str',      '?',    'Str',    'HF',      '?',      '?',      '?',    'HF',    'HF',     '?',      '?',     '?',     '?',     '?',     '?',   'HF',    '?',      '?',     '?',     '?',    '?',     '?',      '?',       'LV',     'LS',    '?',      '?',      '?',     '?',    'LS' };
% ttPosition.h7.YYYYMMDD20180716  = {       '?',      '?',       '?',      '?',    'Str',     '?',      '?',      '?',      '?',    'HF',    'HF',    'HF',    'ctx',    'HF',     '?',     '?',    'HF',    '?',    '?',      '?',     '?',     '?',    '?',     '?',      '?',       'LV',     'LS',    '?',      '?',      '?',    'LS',    'LS' };
% ttPosition.h7.YYYYMMDD20180718  = {       '?',      '?',     'Str',      '?',    'Str',     '?',    'ctx',    'ctx',      '?',    'HF',     '?',    'HF',    'ctx',    'HF',     '?',     '?',    'HF',    '?',    '?',      '?',     '?',     '?',    '?',     '?',      '?',       'LV',     '?',    'LS',      '?',     'LS',    'LS',    'LS' };
% ttPosition.h7.YYYYMMDD20180719  = {     'Str',    'Str',     'Str',      '?',    'Str',     '?',      '?',      '?',      '?',    'HF',    'HF',    'HF',    'ctx',    'HF',    'HF',     '?',    'HF',   'HF',   'HF',      '?',    'HF',    'HF',  'ctx',     '?',      '?',       'LS',     'LS',   'LS',    'ctx',     'LS',    'LS',    'LS' };
% ttPosition.h7.YYYYMMDD20180720  = {     'Str',    'Str',       '?',    'Str',    'Str',     '?',      '?',      '?',      '?',    'HF',    'HF',    'HF',    'ctx',    'HF',    'HF',     '?',    'HF',    '?',   'HF',      '?',    'HF',    'HF',    '?',     '?',      '?',       'LS',      '?',   'LS',    'ctx',     'LS',    'LS',    'LS' };
% ttPosition.h7.YYYYMMDD20180723  = {     'Str',      '?',     'Str',    'Str',    'Str',     '?',    'ctx',      '?',      '?',    'HF',    'HF',    'HF',    'ctx',    'HF',    'HF',     '?',    'HF',    '?',    '?',      '?',    'HF',    'HF',  'ctx',     '?',      '?',       'LS',     'LS',   'LS',    'ctx',     'LS',    'LS',    'LS' };
% ttPosition.h7.YYYYMMDD20180724  = {     'Str',      '?',     'Str',    'Str',    'Str',     '?',    'ctx',      '?',    'Str',    'HF',    'HF',    'HF',    'ctx',    'HF',    'HF',     '?',    'HF',    '?',    '?',      '?',    'HF',    'HF',    '?',     '?',     'LS',        '?',      '?',    '?',      '?',      '?',    'LS',    'LS' };
% ttPosition.h7.YYYYMMDD20180725  = {     'Str',     'LS',     'Str',      '?',    'Str',    'HF',      '?',      '?',    'Str',    'HF',    'HF',    'HF',    'ctx',    'HF',    'HF',     '?',    'HF',    '?',    '?',      '?',    'HF',    'HF',  'ctx',    'HF',     'LS',        '?',   'Thal',    '?',      '?',     'LS',    'LS',    'LS' };
% ttPosition.h7.YYYYMMDD20180726  = {       '?',     'LS',     'Str',    'Str',    'Str',     '?',      '?',    'ctx',    'Str',    'HF',    'HF',    'HF',    'ctx',    'HF',    'HF',    'HF',    'HF',    '?',   'HF',      '?',    'HF',    'HF',    '?',    'HF',     'lS',        '?',   'Thal',   'LS',      '?',      '?',    'LS',    'LS' };
% ttPosition.h7.YYYYMMDD20180727  = {       '?',     'LS',     'Str',    'Str',    'Str',    'HF',    'ctx',    'ctx',    'Str',    'HF',    'HF',    'HF',    'ctx',    'HF',    'HF',    'HF',    'HF',    '?',    '?',      '?',     '?',     '?',    '?',    'HF',     'LS',        '?',   'Thal',   'LS',      '?',      '?',    'LS',    'LS' };
% ttPosition.h7.YYYYMMDD20180730  = {     'Str',     'LS',     'Str',    'Str',    'Str',    'HF',    'ctx',    'ctx',    'Str',    'HF',    'HF',    'HF',    'ctx',    'HF',    'HF',    'HF',    'HF',    '?',    '?',      '?',    'HF',    'HF',    '?',     '?',     'LS',        '?',   'Thal',    '?',     'LS',      '?',    'LS',    'LS' };
% ttPosition.h7.YYYYMMDD20180801a = {     'Str',     'LS',     'Str',    'Str',    'Str',    'HF',    'ctx',    'ctx',    'Str',    'HF',    'HF',    'HF',    'ctx',    'HF',    'HF',    'HF',    'HF',    '?',   'HF',    'ctx',    'HF',    'HF',  'ctx',    'HF',     'LS',     'thal',   'Thal',   'LS',     'LS',     'LS',    'LS',    'LS' };
% ttPosition.h7.YYYYMMDD20180801b = {     'Str',     'LS',     'Str',    'Str',    'Str',    'HF',    'ctx',    'ctx',    'Str',     '?',    'HF',    'HF',    'ctx',    'HF',    'HF',    'HF',    'HF',    '?',   'HF',    'ctx',    'HF',    'HF',  'ctx',    'HF',     'LS',     'thal',   'Thal',   'LS',     'LS',     'LS',     '?',    'LS' };
% ttPosition.h7.YYYYMMDD20180801c = {     'Str',     'LS',     'Str',    'Str',    'Str',    'HF',    'ctx',    'ctx',    'Str',    'HF',    'HF',    'HF',    'ctx',    'HF',    'HF',    'HF',    'HF',    '?',   'HF',    'ctx',    'HF',    'HF',  'ctx',    'HF',     'LS',     'thal',   'Thal',   'LS',     'LS',     'LS',    'LS',    'LS' };
% ttPosition.h7.YYYYMMDD20180802  = {     'Str',     'LS',     'Str',    'Str',    'Str',     '?',    'ctx',    'ctx',    'Str',    'HF',    'HF',    'HF',    'ctx',    'HF',    'HF',    'HF',    'HF',    '?',   'HF',    'ctx',    'HF',    'HF',    '?',    'HF',     'LS',     'thal',   'Thal',   'LS',     'LS',      '?',    'LS',     '?' };
% ttPosition.h7.YYYYMMDD20180803a = {     'Str',     'LS',     'Str',      '?',    'Str',    'HF',      '?',    'ctx',      '?',    'HF',    'HF',    'HF',    'ctx',    'HF',    'HF',     '?',    'HF',    '?',   'HF',    'ctx',    'HF',    'HF',    '?',    'HF',     'LS',     'thal',   'Thal',    '?',     'LS',      '?',    'LS',    'LS' };
% ttPosition.h7.YYYYMMDD20180803b = {     'Str',     'LS',     'Str',    'Str',    'Str',     '?',    'ctx',    'ctx',      '?',    'HF',    'HF',    'HF',    'ctx',    'HF',    'HF',    'HF',    'HF',    '?',    '?',    'ctx',    'HF',    'HF',    '?',    'HF',     'LS',    'nReun',   'Thal',    '?',     'LS',      '?',    'LS',    'LS' };
% ttPosition.h7.YYYYMMDD20180806  = {     'Str',    'SHy',     'Str',    'Str',    'Str',    'HF',    'ctx',    'ctx',      '?',    'HF',    'HF',    'HF',    'ctx',    'HF',    'HF',    'HF',    'HF',    '?',   'HF',    'ctx',    'HF',    'HF',    '?',    'HF',     'LS',    'nReun',      '?',   'LS',     'LS',      '?',    'LS',    'LS' };
% ttPosition.h7.YYYYMMDD20180807  = {     'Str',    'SHy',     'Str',    'Str',    'Str',    'HF',    'ctx',    'ctx',      '?',    'HF',    'HF',    'HF',    'ctx',    'HF',    'HF',    'HF',    'HF',    '?',    '?',    'ctx',    'HF',    'HF',    '?',     '?',     'LS',    'nReun',     'AM',    '?',     'LS',      '?',     '?',    'LS' };
% ttPosition.h7.YYYYMMDD20180808  = {     'Str',    'SHy',      'LV',      '?',    'Str',    'HF',    'ctx',    'ctx',    'Str',    'HF',    'HF',    'HF',    'ctx',    'HF',    'HF',    'HF',    'HF',    '?',    '?',    'ctx',    'HF',    'HF',    '?',     '?',     'LS',    'nReun',     'AM',    '?',     'LS',   'hyTh',    'LS',    'LS' };
% ttPosition.h7.YYYYMMDD20180809  = {     'Str',      '?',    'BNST',    'Str',    'Str',    'HF',    'ctx',    'ctx',    'Str',    'HF',    'HF',    'HF',    'ctx',    'HF',    'HF',    'HF',    'HF',    '?',    '?',    'ctx',     '?',     '?',    '?',    'HF',     'LS',    'nReun',     'AM',    '?',      '?',      '?',    'LS',    'LS' };
% ttPosition.h7.YYYYMMDD20180810  = {     'Str',    'LPO',    'BNST',    'Str',    'Str',    'HF',    'ctx',      '?',    'Str',    'HF',    'HF',    'HF',    'ctx',    'HF',    'HF',    'HF',    'HF',    '?',    '?',    'ctx',    'HF',    'HF',    '?',     '?',     'LS',    'nReun',      '?',    '?',   'hyTh',   'hyTh',    'LS',    'LS' };
% ttPosition.h7.YYYYMMDD20180813  = {     'Str',    'LPO',    'BNST',    'Str',    'Str',     '?',    'ctx',      '?',    'Str',     '?',    'HF',    'HF',    'ctx',    'HF',    'HF',    'HF',    'HF',    '?',    '?',    'ctx',    'HF',    'HF',    '?',     '?',    'vhc',    'nReun',  'nReun',   'LS',   'hyTh',   'hyTh',    'LS',    'LS' };
% ttPosition.h7.YYYYMMDD20180814  = {    'BNST',      '?',    'BNST',      '?',    'Str',     '?',      '?',      '?',    'Str',     '?',    'HF',    'HF',    'ctx',    'HF',    'HF',    'HF',    'HF',    '?',    '?',      '?',    'HF',    'HF',    '?',    'HF',    'vhc',    'nReun',      '?',    '?',      '?',   'hyTh',    'LS',    'LS' };
% ttPosition.h7.YYYYMMDD20180815  = {    'BNST',    'MPA',    'BNST',    'Str',    'Str',    'HF',    'ctx',      '?',    'Str',     '?',    'HF',    'HF',    'ctx',    'HF',    'HF',     '?',    'HF',    '?',    '?',      '?',    'HF',    'HF',    '?',    'HF',    'vhc',    'nReun',      '?',    '?',      '?',   'hyTh',     '?',    'LS' };
% ttPosition.h7.YYYYMMDD20180822  = {    'BNST',    'MPA',    'BNST',    'Str',    'Str',    'HF',    'ctx',    'ctx',    'Str',    'HF',    'HF',    'HF',    'ctx',    'HF',    'HF',    'HF',    'HF',    '?',   'HF',    'ctx',    'HF',    'HF',  'ctx',    'HF',    'vhc',    'nReun',    'LPO',   'LS',   'hyTh',   'hyTh',    'LS',    'LS' };
% ttPosition.h7.YYYYMMDD20180827  = {       '?',      '?',       '?',      '?',      '?',     '?',      '?',      '?',      '?',     '?',     '?',    '?',       '?',     '?',     '?',     '?',     '?',    '?',    '?',      '?',     '?',     '?',    '?',     '?',      '?',        '?',      '?',    '?',      '?',      '?',     '?',     '?' };
% ttPosition.h7.YYYYMMDD20180828  = {     'MPA',    'MPA',     'LPO',    'Str',      '?',     '?',    'ctx',    'ctx',    'Str',    'HF',    'HF',    'HF',    'ctx',    'HF',    'HF',    'HF',    'HF',    '?',    '?',      '?',    'HF',    'HF',  'ctx',    'HF',    'PVA',        '?',      '?',   'LS',   'hyTh',   'hyTh',  'hyTh',  'hyTh' };
% ttPosition.h7.YYYYMMDD20180831  = {       '?',      '?',       '?',      '?',      '?',     '?',      '?',      '?',      '?',     '?',    'HF',    'HF',    'ctx',    'HF',    'HF',    'HF',    'HF',    '?',    '?',      '?',     '?',     '?',    '?',    'HF',    'PVA',        '?',      '?',    '?',      '?',      '?',  'hyTh',  'hyTh' };
% ttPosition.h7.YYYYMMDD20180904  = {     'MPA',    'MPA',     'LPO',    'Str',      '?',    'HF',    'ctx',    'ctx',    'Str',    'HF',    'HF',    'HF',    'ctx',    'HF',    'HF',     '?',     '?',    '?',    '?',    'ctx',     '?',     '?',  'ctx',    'HF',    'PVA',     'hyTh',    'LPO',   'LS',   'hyTh',   'hyTh',  'hyTh',  'hyTh' };
% ttPosition.h7.YYYYMMDD20180905  = {       '?',      '?',       '?',      '?',      '?',     '?',      '?',      '?',    'Str',    'HF',    'HF',    'HF',    'ctx',    'HF',    'HF',    'HF',    'HF',    '?',    '?',    'ctx',     '?',     '?',    '?',    'HF',    'PVA',        '?',      '?',    '?',      '?',      '?',     '?',     '?' };
% 
% 
% ttPosition.h1.YYYYMMDD20180809  = {    'NAc',    '?',    'Str',    'HF',   'ctx',    'HF',    '?',     '?',    'HF',    'PAG',    '?',    'VTA',      '?',    'retF',    'VTA',    '?',    'HF',    '?',    '?',    '?',      '?',    'HF',    '?',    '?' };
% ttPosition.h1.YYYYMMDD20180810  = {    'NAc',    '?',    'Str',    'HF',   'ctx',    'HF',    '?',     '?',    'HF',    'PAG',    '?',    'VTA',    'VTA',    'retF',    'VTA',    '?',    'HF',    '?',    '?',    '?',      '?',    'HF',    '?',    '?' };
% ttPosition.h1.YYYYMMDD20180813  = {    'NAc',    '?',    'Str',    'HF',   'ctx',    'HF',    '?',     '?',    'HF',    'PAG',    '?',    'VTA',      '?',    'retF',    'VTA',    '?',    'HF',    '?',    '?',    '?',      '?',    'HF',    '?',    '?' };
% ttPosition.h1.YYYYMMDD20180814  = {    'NAc',    '?',    'Str',    'HF',   'ctx',    'HF',    '?',     '?',    'HF',      '?',    '?',    'VTA',    'VTA',       '?',    'VTA',    '?',    'HF',    '?',    '?',    '?',      '?',    'HF',    '?',    '?' };
% ttPosition.h1.YYYYMMDD20180815  = {    'NAc',    '?',    'Str',    'HF',   'ctx',    'HF',    '?',     '?',    'HF',    'PAG',    '?',    'VTA',    'VTA',    'retF',    'VTA',    '?',    'HF',    '?',    '?',    '?',      '?',    'HF',    '?',    '?' };
% ttPosition.h1.YYYYMMDD20180817  = {    'NAc',    '?',    'Str',     '?',     '?',     '?',    '?',     '?',     '?',    'PAG',    '?',    'VTA',    'VTA',    'retF',    'VTA',    '?',     '?',    '?',    '?',    '?',      '?',    'HF',    '?',    '?' };
% ttPosition.h1.YYYYMMDD20180822  = {    'NAc',    '?',    'Str',    'HF',     '?',    'HF',    '?',     '?',    'HF',    'PAG',    '?',    'VTA',    'VTA',    'retF',    'VTA',    '?',    'HF',    '?',    '?',    '?',    'ctx',    'HF',    '?',    '?' };
% ttPosition.h1.YYYYMMDD20180823  = {    'NAc',    '?',    'Str',    'HF',    'HF',    'HF',    '?',    'HF',    'HF',    'PAG',    '?',    'VTA',    'VTA',    'retF',    'VTA',    '?',     '?',    '?',    '?',    '?',    'ctx',    'HF',    '?',    '?' };
% ttPosition.h1.YYYYMMDD20180824  = {    'NAc',    '?',    'Str',    'HF',    'HF',    'HF',    '?',    'HF',    'HF',    'PAG',    '?',    'VTA',    'VTA',    'retF',    'VTA',    '?',    'HF',    '?',    '?',    '?',    'ctx',    'HF',    '?',    '?' };
% ttPosition.h1.YYYYMMDD20180827a = {    'NAc',    '?',    'Str',     '?',    'HF',    'HF',    '?',     '?',     '?',    'PAG',    '?',    'VTA',    'VTA',    'retF',    'VTA',    '?',    'HF',    '?',    '?',    '?',    'ctx',    'HF',    '?',    '?' };
% ttPosition.h1.YYYYMMDD20180827b = {    'NAc',    '?',    'Str',    'HF',    'HF',    'HF',    '?',    'HF',    'HF',    'PAG',    '?',    'VTA',    'VTA',       '?',    'VTA',    '?',    'HF',    '?',    '?',    '?',    'ctx',    'HF',    '?',    '?' };
% ttPosition.h1.YYYYMMDD20180828  = {    'NAc',    '?',    'Str',    'HF',    'HF',    'HF',    '?',    'HF',    'HF',    'PAG',    '?',    'VTA',    'VTA',     'PAG',    'VTA',    '?',    'HF',    '?',    '?',    '?',    'ctx',    'HF',    '?',    '?' };
% ttPosition.h1.YYYYMMDD20180829  = {    'NAc',    '?',    'Str',    'HF',    'HF',    'HF',    '?',    'HF',    'HF',    'PAG',    '?',      '?',      '?',     'PAG',    'VTA',    '?',    'HF',    '?',    '?',    '?',    'ctx',    'HF',    '?',    '?' };
% ttPosition.h1.YYYYMMDD20180830  = {    'NAc',    '?',    'Str',     '?',     '?',     '?',    '?',    'HF',    'DG',    'PAG',    '?',      '?',    'VTA',     'PAG',    'VTA',    '?',     '?',    '?',    '?',    '?',      '?',    'HF',    '?',    '?' };
% ttPosition.h1.YYYYMMDD20180831  = {    'NAc',    '?',    'Str',    'HF',     '?',    'HF',    '?',    'HF',    'DG',    'PAG',    '?',      '?',    'VTA',       '?',    'VTA',    '?',    'HF',    '?',    '?',    '?',    'ctx',    'HF',    '?',    '?' };
% ttPosition.h1.YYYYMMDD20180904  = {    'NAc',    '?',    'Str',    'HF',     '?',    'HF',    '?',    'HF',    'DG',    'PAG',    '?',      '?',    'VTA',       '?',    'VTA',    '?',    'HF',    '?',    '?',    '?',    'ctx',    'HF',    '?',    '?' };
% ttPosition.h1.YYYYMMDD20180905  = {    'NAc',    '?',    'Str',     '?',    'HF',     '?',    '?',    'HF',     '?',    'PAG',    '?',      '?',    'VTA',     'PAG',    'VTA',    '?',    'HF',    '?',    '?',    '?',    'ctx',    'HF',    '?',    '?' };
% ttPosition.h1.YYYYMMDD20180906  = {    'NAc',    '?',    'Str',    'HF',    'HF',    'HF',    '?',    'HF',     '?',    'PAG',    '?',      '?',    'VTA',       '?',    'VTA',    '?',    'HF',    '?',    '?',    '?',    'ctx',    'HF',    '?',    '?' };
% ttPosition.h1.YYYYMMDD20180907  = {    'NAc',    '?',    'Str',    'HF',    'HF',     '?',    '?',    'HF',    'HF',    'PAG',    '?',      '?',    'VTA',       '?',    'VTA',    '?',    'HF',    '?',    '?',    '?',    'ctx',    'HF',    '?',    '?' };
% ttPosition.h1.YYYYMMDD20180908  = {    'NAc',    '?',    'Str',    'HF',    'HF',    'HF',    '?',    'HF',    'HF',    'PAG',    '?',      '?',    'VTA',       '?',    'VTA',    '?',    'HF',    '?',    '?',    '?',    'ctx',    'HF',    '?',    '?' };
% ttPosition.h1.YYYYMMDD20180909  = {    'NAc',    '?',      '?',    'HF',    'HF',    'HF',    '?',    'HF',     '?',    'PAG',    '?',      '?',    'VTA',       '?',    'VTA',    '?',    'HF',    '?',    '?',    '?',    'ctx',    'HF',    '?',    '?' };
% ttPosition.h1.YYYYMMDD20180914  = {    'NAc',    '?',    'Str',    'HF',    'HF',    'HF',    '?',    'HF',    'HF',    'PAG',    '?',    'VTA',    'VTA',       '?',    'VTA',    '?',    'HF',    '?',    '?',    '?',    'ctx',    'HF',    '?',    '?' };
% 
% 
% ttPosition.da10.YYYYMMDD20170911  = {      '?',      '?',    '?',    '?',     '?',    '?',    '?',    '?',    '?',    '?',    '?',       '?',    '?',    'HF',    '?',    '?',     '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?' };
% ttPosition.da10.YYYYMMDD20170911b = {      '?',      '?',    '?',    '?',     '?',    '?',    '?',    '?',    '?',    '?',    '?',       '?',    '?',     '?',    '?',    '?',     '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?' };
% ttPosition.da10.YYYYMMDD20170912  = {      '?',      '?',    '?',    '?',     '?',    '?',    '?',    '?',    '?',    '?',    '?',       '?',    '?',     '?',    '?',    '?',     '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?' };
% ttPosition.da10.YYYYMMDD20170913  = {      '?',      '?',    '?',    '?',     '?',    '?',    '?',    '?',    '?',    '?',    '?',       '?',    '?',     '?',    '?',    '?',     '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?' };
% ttPosition.da10.YYYYMMDD20170914  = {      '?',      '?',    '?',    '?',     '?',    '?',    '?',    '?',    '?',    '?',    '?',    'retF',    '?',    'HF',    '?',    '?',     '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?' };
% ttPosition.da10.YYYYMMDD20170915  = {      '?',    'Str',    '?',    '?',     '?',    '?',    '?',    '?',    '?',    '?',    '?',    'retF',    '?',    'HF',    '?',    '?',     '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?' };
% ttPosition.da10.YYYYMMDD20170918  = {    'Str',    'Str',    '?',    '?',    'HF',    '?',    '?',    '?',    '?',    '?',    '?',    'retF',    '?',    'HF',    '?',    '?',     '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?' };
% ttPosition.da10.YYYYMMDD20170919  = {      '?',    'Str',    '?',    '?',     '?',    '?',    '?',    '?',    '?',    '?',    '?',    'retF',    '?',    'HF',    '?',    '?',     '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?' };
% ttPosition.da10.YYYYMMDD20170920  = {      '?',    'Str',    '?',    '?',     '?',    '?',    '?',    '?',    '?',    '?',    '?',    'retF',    '?',    'HF',    '?',    '?',    'HF',    '?',    '?',    '?',    '?',    '?',    '?',    '?' };
% ttPosition.da10.YYYYMMDD20170920b = {      '?',      '?',    '?',    '?',     '?',    '?',    '?',    '?',    '?',    '?',    '?',    'retF',    '?',    'HF',    '?',    '?',    'HF',    '?',    '?',    '?',    '?',    '?',    '?',    '?' };
% ttPosition.da10.YYYYMMDD20170922  = {      '?',    'Str',    '?',    '?',     '?',    '?',    '?',    '?',    '?',    '?',    '?',    'retF',    '?',    'HF',    '?',    '?',    'HF',    '?',    '?',    '?',    '?',    '?',    '?',    '?' };
% ttPosition.da10.YYYYMMDD20170925  = {      '?',    'Str',    '?',    '?',     '?',    '?',    '?',    '?',    '?',    '?',    '?',    'retF',    '?',    'HF',    '?',    '?',    'HF',    '?',    '?',    '?',    '?',    '?',    '?',    '?' };
% 
% 
% ttPosition.da5.YYYYMMDD20160822 = {   '?',     '?',       '?',       '?',      '?',      '?',     '?',     '?',    '?',     '?',     '?',     '?',    '?',      '?',      '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?' };
% ttPosition.da5.YYYYMMDD20160823 = {   '?',     '?',       '?',       '?',      '?',      '?',     '?',     '?',    '?',     '?',     '?',     '?',    '?',      '?',      '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?' };
% ttPosition.da5.YYYYMMDD20160824 = {   '?',     '?',    'retF',     'VTA',      '?',    'Str',     '?',     '?',    '?',     '?',     '?',     '?',    '?',      '?',      '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?' };
% ttPosition.da5.YYYYMMDD20160825 = {   '?',     '?',       '?',       '?',      '?',      '?',     '?',     '?',    '?',     '?',     '?',     '?',    '?',      '?',      '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?' };
% ttPosition.da5.YYYYMMDD20160826 = {   '?',     '?',       '?',       '?',      '?',      '?',     '?',     '?',    '?',     '?',     '?',     '?',    '?',      '?',      '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?' };
% ttPosition.da5.YYYYMMDD20160827 = {   '?',    'HF',       '?',       '?',    'Str',      '?',    'HF',    'HF',    '?',    'HF',     '?',     '?',    '?',    'Str',    'Str',    '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?' };
% ttPosition.da5.YYYYMMDD20160828 = {   '?',     '?',       '?',       '?',      '?',      '?',     '?',     '?',    '?',     '?',     '?',     '?',    '?',      '?',      '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?' };
% ttPosition.da5.YYYYMMDD20160829 = {  'HF',    'HF',       '?',       '?',    'Str',      '?',    'HF',    'HF',    '?',    'HF',     '?',     '?',    '?',    'Str',    'Str',    '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?' };
% ttPosition.da5.YYYYMMDD20160830 = {  'HF',     '?',       '?',       '?',    'Str',      '?',    'HF',    'HF',    '?',    'HF',     '?',     '?',    '?',    'Str',    'Str',    '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?' };
% ttPosition.da5.YYYYMMDD20160831 = {   '?',    'HF',       '?',       '?',    'Str',      '?',    'HF',    'HF',    '?',    'HF',     '?',     '?',    '?',    'Str',    'Str',    '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?' };
% ttPosition.da5.YYYYMMDD20160901 = {  'HF',    'HF',       '?',       '?',    'Str',      '?',    'HF',    'HF',    '?',    'HF',     '?',     '?',    '?',    'Str',    'Str',    '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?' };
% ttPosition.da5.YYYYMMDD20160902 = {  'HF',     '?',       '?',       '?',    'Str',      '?',    'HF',    'HF',    '?',    'HF',     '?',     '?',    '?',    'Str',    'Str',    '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?' };
% ttPosition.da5.YYYYMMDD20160906 = {  'HF',    'HF',       '?',     'VTA',    'Str',      '?',    'HF',    'HF',    '?',    'HF',     '?',    'HF',    '?',    'Str',    'Str',    '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?' };
% ttPosition.da5.YYYYMMDD20160907 = {  'HF',    'HF',    'retF',     'VTA',    'Str',      '?',    'HF',    'HF',    '?',    'HF',     '?',     '?',    '?',    'Str',    'Str',    '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?' };
% ttPosition.da5.YYYYMMDD20160908 = {  'HF',     '?',    'retF',     'VTA',    'Str',    'Str',    'HF',    'HF',    '?',    'HF',    'HF',    'HF',    '?',    'Str',    'Str',    '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?',    '?' };





%% OLD VERSION 1

% % to extract data, do something like the following : 
% % tt = 5
% % dd='2018-06-11'
% % ttPosition.h5.(strcat('YYYYMMDD',(strrep(dd,'-','')))){tt}
% 
% ttPosition.h5.YYYYMMDD20180425 = { '?' , '?' , '?'  , '?'  , 'Str', 'Str', '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , 'CA1', '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , 'CA1', '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'   };
% ttPosition.h5.YYYYMMDD20180427 = { '?' , '?' , 'Str', 'Str', 'Str', 'Str', '?'  , 'ctx', 'ctx', 'CA1', '?'  , '?'  , '?'  , 'CA1', 'CA1', '?'  , '?'  , '?'  , 'CA1', 'CA1', '?'  , 'CA1', '?'  , 'CA1', 'ctx', '?'  , '?'  , '?'  , '?'  , 'ctx', '?'  , 'Str' };
% ttPosition.h5.YYYYMMDD20180501 = { '?' , '?' , '?'  , 'Str', 'Str', 'Str', '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , 'CA1', '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'   };
% ttPosition.h5.YYYYMMDD20180502 = { '?' , '?' , '?'  , 'Str', 'Str', 'Str', '?'  , 'ctx', '?'  , 'CA1', '?'  , 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', '?'  , '?'  , '?'  , 'CA1', '?'  , '?'  , '?'  , '?'  , '?'  , 'ctx', 'Str', '?'  , 'Str', '?'  , '?'  , 'Str' };
% ttPosition.h5.YYYYMMDD20180503 = { '?' , '?' , '?'  , '?'  , 'Str', 'Str', '?'  , 'ctx', '?'  , '?'  , '?'  , 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', '?'  , '?'  , 'CA1', '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , 'Str', '?'  , '?'  , '?'  , '?'  , '?'   };
% ttPosition.h5.YYYYMMDD20180507 = { '?' , '?' , '?'  , 'Str', 'Str', 'Str', '?'  , 'ctx', '?'  , '?'  , '?'  , '?'  , 'CA1', 'CA1', 'CA1', '?'  , 'CA1', '?'  , 'CA1', 'CA1', 'CA1', '?'  , '?'  , 'CA1', 'ctx', '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'   };
% ttPosition.h5.YYYYMMDD20180508 = { '?' , '?' , '?'  , '?'  , 'Str', 'Str', '?'  , 'ctx', '?'  , '?'  , '?'  , 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', '?'  , 'CA1', 'CA1', 'CA1', '?'  , '?'  , '?'  , '?'  , '?'  , 'Str', '?'  , '?'  , '?'  , '?'  , '?'   };
% ttPosition.h5.YYYYMMDD20180509 = { '?' , '?' , '?'  , 'Str', 'Str', 'Str', '?'  , 'ctx', '?'  , '?'  , '?'  , 'CA1', 'CA1', '?'  , '?'  , 'CA1', 'CA1', '?'  , '?'  , 'CA1', 'CA1', '?'  , '?'  , '?'  , 'ctx', 'ctx', 'Str', '?'  , '?'  , '?'  , 'Str', '?'   };
% ttPosition.h5.YYYYMMDD20180511 = { 'LS', 'LS', '?'  , 'Str', 'Str', 'Str', '?'  , 'ctx', 'ctx', '?'  , '?'  , 'CA1', 'CA1', '?'  , '?'  , 'CA1', 'CA1', '?'  , 'CA1', '?'  , 'CA1', '?'  , '?'  , '?'  , '?'  , '?'  , 'Str', 'Str', '?'  , '?'  , 'Str', '?'   };
% ttPosition.h5.YYYYMMDD20180514 = { '?' , '?' , '?'  , 'LS' , 'Str', 'Str', '?'  , 'ctx', '?'  , '?'  , '?'  , 'CA1', 'CA1', 'CA1', '?'  , 'CA1', 'CA1', '?'  , '?'  , 'CA1', 'CA1', 'CA1', '?'  , '?'  , '?'  , '?'  , 'LS' , 'LS' , 'LS' , 'Str', 'LS' , 'LS'  };
% ttPosition.h5.YYYYMMDD20180515 = { 'LS', 'LS', '?'  , 'LS' , 'LS' , 'Str', '?'  , 'ctx', '?'  , '?'  , '?'  , 'CA1', 'CA1', '?'  , '?'  , 'CA1', 'CA1', '?'  , '?'  , 'CA1', 'CA1', '?'  , '?'  , '?'  , 'ctx', '?'  , 'LS' , 'LS' , 'LS' , '?'  , 'LS' , 'LS'  };
% ttPosition.h5.YYYYMMDD20180516 = { '?' , '?' , '?'  , '?'  , 'LS' , 'Str', '?'  , 'ctx', '?'  , 'CA1', '?'  , 'CA1', 'CA1', '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , 'CA1', 'CA1', '?'  , '?'  , 'CA1', 'ctx', '?'  , 'LS' , 'LS' , 'LS' , '?'  , 'LS' , 'LS'  };
% ttPosition.h5.YYYYMMDD20180518 = { 'LS', '?' , '?'  , '?'  , 'LS' , 'LS' , '?'  , 'ctx', '?'  , '?'  , '?'  , '?'  , 'CA1', 'CA1', '?'  , '?'  , 'CA1', '?'  , '?'  , 'CA1', 'CA1', 'CA1', '?'  , 'CA1', 'ctx', '?'  , 'LS' , 'LS' , 'LS' , '?'  , 'LS' , 'LS'  };
% ttPosition.h5.YYYYMMDD20180608 = { '?' , 'LS', '?'  , '?'  , 'LS' , 'LS' , '?'  , 'ctx', 'ctx', 'CA1', '?'  , 'CA1', 'CA1', '?'  , '?'  , 'CA1', '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , 'ctx', 'ctx', 'LS' , '?'  , 'LS' , '?'  , '?'  , '?'   };
% ttPosition.h5.YYYYMMDD20180611 = { 'LS', '?' , '?'  , 'LS' , 'LS' , 'LS' , '?'  , '?'  , 'ctx', 'CA1', '?'  , 'CA1', 'CA1', '?'  , '?'  , 'CA1', '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , 'ctx', '?'  , 'LS' , 'LS' , '?'  , '?'  , '?'  , 'LS'  };
% ttPosition.h5.YYYYMMDD20180612 = { '?' , '?' , '?'  , '?'  , 'LS' , 'LS' , '?'  , 'ctx', '?'  , 'CA1', '?'  , 'CA1', 'CA1', '?'  , '?'  , 'CA1', '?'  , '?'  , '?'  , '?'  , '?'  , 'CA1', '?'  , '?'  , 'ctx', '?'  , '?'  , '?'  , 'LS' , '?'  , 'LS' , '?'   };
% ttPosition.h5.YYYYMMDD20180613 = { 'LS', '?' , 'Str', '?'  , 'LS' , 'LS' , '?'  , 'ctx', '?'  , 'CA1', '?'  , 'CA1', 'CA1', '?'  , 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', '?'  , 'CA1', 'CA1', '?'  , 'CA1', 'ctx', 'ctx', 'LS' , 'LS' , 'LS' , '?'  , 'LS' , 'LS'  };
% ttPosition.h5.YYYYMMDD20180614 = { 'LS', '?' , '?'  , '?'  , 'LS' , 'LS' , '?'  , 'ctx', 'ctx', 'CA1', '?'  , 'CA1', 'CA1', '?'  , '?'  , 'CA1', '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , 'ctx', 'ctx', 'LS' , 'LS' , 'LS' , 'Str', 'LS' , 'LS'  };
% ttPosition.h5.YYYYMMDD20180615 = { 'LS', '?' , '?'  , '?'  , 'LS' , 'LS' , '?'  , 'ctx', '?'  , 'CA1', '?'  , '?'  , 'CA1', '?'  , '?'  , 'CA1', '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , 'LS' , 'LS' , 'LS' , '?'  , '?'  , 'LS'  };
% 
% 
% ttPosition.h7.YYYYMMDD20180705  = {  'Str', 'LS'  , 'Str', '?'  , 'Str', '?'  , 'ctx', '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'   , '?'   , '?'   , '?'   , '?'   , '?'   , 'CA1' , '?'   , '?'    , '?'       , '?'       , '?'       , '?'       , '?'   , 'LS' };
% ttPosition.h7.YYYYMMDD20180706  = {  'Str', '?'   , 'Str', '?'  , '?'  , 'CA1', '?'  , '?'  , '?'  , 'CA1', '?'  , 'CA1', '?'  , 'CA1', 'CA1', 'CA1', 'CA1', '?'   , '?'   , '?'   , '?'   , '?'   , '?'   , '?'   , 'LS'  , '?'    , '?'       , '?'       , '?'       , '?'       , '?'   , '?'  };
% ttPosition.h7.YYYYMMDD20180711  = {  'Str', 'LS'  , 'Str', '?'  , 'Str', 'CA1', '?'  , '?'  , 'Str', 'CA1', '?'  , '?'  , 'CA1', 'CA1', 'CA1', '?'  , '?'  , '?'   , 'CA1' , '?'   , '?'   , '?'   , '?'   , 'CA1' , 'LS'  , '?'    , '?'       , '?'       , '?'       , '?'       , '?'   , 'LS' };
% ttPosition.h7.YYYYMMDD20180712  = {  'Str', 'LS_V', 'Str', '?'  , 'Str', 'CA1', '?'  , 'ctx', 'Str', '?'  , '?'  , '?'  , 'CA1', '?'  , 'CA1', '?'  , '?'  , '?'   , '?'   , '?'   , '?'   , '?'   , '?'   , '?'   , 'LS'  , '?'    , 'LS_SFi'  , '?'       , '?'       , '?'       , 'LS'  , 'LS' };
% ttPosition.h7.YYYYMMDD20180713  = {  'Str', 'LS_V', 'Str', '?'  , 'Str', 'CA1', '?'  , '?'  , '?'  , 'CA1', 'CA1', '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , 'CA1' , '?'   , '?'   , '?'   , '?'   , '?'   , '?'   , '?'   , '?'    , 'LS_SFi'  , '?'       , '?'       , '?'       , '?'   , 'LS' };
% ttPosition.h7.YYYYMMDD20180716  = {  '?'  , '?'   , '?'  , '?'  , 'Str', '?'  , '?'  , '?'  , '?'  , 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', '?'  , '?'  , 'CA1', '?'   , '?'   , '?'   , '?'   , '?'   , '?'   , '?'   , '?'   , '?'    , 'LS_SFi'  , '?'       , '?'       , '?'       , 'LS'  , 'LS' };
% ttPosition.h7.YYYYMMDD20180718  = {  '?'  , '?'   , 'Str', '?'  , 'Str', '?'  , 'ctx', 'ctx', '?'  , 'CA1', '?'  , 'CA1', 'CA1', 'CA1', '?'  , '?'  , 'CA1', '?'   , '?'   , '?'   , '?'   , '?'   , '?'   , '?'   , '?'   , '?'    , '?'       , 'LS_SFi'  , '?'       , 'LS_SFi'  , 'LS'  , 'LS' };
% ttPosition.h7.YYYYMMDD20180719  = {  'Str', 'LS_V', 'Str', '?'  , 'Str', '?'  , '?'  , '?'  , '?'  , 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', '?'  , 'CA1', 'CA1' , 'CA1' , '?'   , 'CA1' , 'CA1' , 'CA1' , '?'   , '?'   , 'LS_SFi', 'LS_SFi' , 'LS_SFi'  , 'LS_SFi'  , 'LS_SFi'  , 'LS'  , 'LS' };
% ttPosition.h7.YYYYMMDD20180720  = {  'Str', 'LS_V', '?'  , 'Str', 'Str', '?'  , '?'  , '?'  , '?'  , 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', '?'  , 'CA1', '?'   , 'CA1' , '?'   , 'CA1' , 'CA1' , '?'   , '?'   , '?'   , 'LS_SFi', '?'      , 'LS_SFi'  , 'LS_SFi'  , 'LS_SFi'  , 'LS'  , 'LS' };
% ttPosition.h7.YYYYMMDD20180723  = {  'Str', '?'   , 'Str', 'Str', 'Str', '?'  , 'ctx', '?'  , '?'  , 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', '?'  , 'CA1', '?'   , '?'   , '?'   , 'CA1' , 'CA1' , 'CA1' , '?'   , '?'   , 'LS_SFi', 'LS_SFi' , 'LS_SFi'  , 'LS_SFi'  , 'LS_SFi'  , 'LS'  , 'LS' };
% ttPosition.h7.YYYYMMDD20180724  = {  'Str', '?'   , 'Str', 'Str', 'Str', '?'  , 'ctx', '?'  , 'Str', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', '?'  , 'CA1', '?'   , '?'   , '?'   , 'CA1' , 'CA1' , '?'   , '?'   , 'LS'  , '?'    , '?'       , '?'       , '?'       , '?'       , 'LS'  , 'LS' };
% ttPosition.h7.YYYYMMDD20180725  = {  'Str', 'BST' , 'Str', '?'  , 'Str', 'CA1', '?'  , '?'  , 'Str', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', '?'  , 'CA1', '?'   , '?'   , '?'   , 'CA1' , 'CA1' , 'CA1' , 'CA1' , 'LS'  , '?'    , 'Thal'    , '?'       , '?'       , 'LS_SFi'  , 'LS'  , 'LS' };
% ttPosition.h7.YYYYMMDD20180726  = {  '?'  , 'BST' , 'Str', 'Str', 'Str', '?'  , '?'  , 'Str', 'Str', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', '?'   , 'CA1' , '?'   , 'CA1' , 'CA1' , '?'   , 'CA1' , 'LS'  , '?'    , 'Thal'    , 'Thal'    , '?'       , '?'       , 'LS'  , 'LS' };
% ttPosition.h7.YYYYMMDD20180727  = {  '?'  , 'BST' , 'Str', 'Str', 'Str', 'CA1', 'Str', 'Str', 'Str', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', '?'   , '?'   , '?'   , '?'   , '?'   , '?'   , 'CA1' , 'LS'  , '?'    , 'Thal'    , 'Thal'    , '?'       , '?'       , 'LS'  , 'LS' };
% ttPosition.h7.YYYYMMDD20180730  = {  'Str', 'BST' , 'Str', 'Str', 'Str', 'CA1', 'Str', 'Str', 'Str', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', '?'   , '?'   , '?'   , 'CA1' , 'CA1' , '?'   , '?'   , 'LS'  , '?'    , 'Thal'    , '?'       , 'Thal'    , '?'       , 'LS'  , 'LS' };
% ttPosition.h7.YYYYMMDD20180801a = {  'Str', 'SI'  , 'Str', 'Str', 'Str', 'CA1', 'Str', 'Str', 'Str', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', '?'   , 'CA1' , 'CA1' , 'CA1' , 'CA1' , 'CA1' , 'CA1' , 'LS'  , 'Thal' , 'Thal'    , 'Thal'    , 'Thal'    , 'Thal'    , 'LS'  , 'LS' };
% ttPosition.h7.YYYYMMDD20180801b = {  'Str', 'SI'  , 'Str', 'Str', 'Str', 'CA1', 'Str', 'Str', 'Str', '?'  , 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', '?'   , 'CA1' , 'CA1' , 'CA1' , 'CA1' , 'CA1' , 'CA1' , 'LS'  , 'Thal' , 'Thal'    , 'Thal'    , 'Thal'    , 'Thal'    , '?'   , 'LS' };
% ttPosition.h7.YYYYMMDD20180801c = {  'Str', 'SI'  , 'Str', 'Str', 'Str', 'CA1', 'Str', 'Str', 'Str', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', '?'   , 'CA1' , 'CA1' , 'CA1' , 'CA1' , 'CA1' , 'CA1' , 'LS'  , 'Thal' , 'Thal'    , 'Thal'    , 'Thal'    , 'Thal'    , 'LS'  , 'LS' };
% ttPosition.h7.YYYYMMDD20180802  = {  'Str', 'SI'  , 'Str', 'Str', 'Str', '?'  , 'Str', 'Str', 'Str', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', '?'   , 'CA1' , 'CA1' , 'CA1' , 'CA1' , '?'   , 'CA1' , 'LS'  , 'Thal' , 'Thal'    , 'Thal'    , 'Thal'    , '?'       , 'LS'  , '?'  };
% ttPosition.h7.YYYYMMDD20180803a = {  'Str', 'SI'  , 'Str', '?'  , 'Str', 'CA1', '?'  , 'Str', '?'  , 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', '?'  , 'CA1', '?'   , 'CA1' , 'CA1' , 'CA1' , 'CA1' , '?'   , 'CA1' , 'LS'  , 'Thal' , 'Thal'    , '?'       , 'Thal'    , '?'       , 'LS'  , 'LS' };
% ttPosition.h7.YYYYMMDD20180803b = {  'Str', 'SI'  , 'Str', 'Str', 'Str', '?'  , 'Str', 'Str', '?'  , 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', '?'   , '?'   , 'CA1' , 'CA1' , 'CA1' , '?'   , 'CA1' , 'LS'  , 'Thal' , 'Thal'    , '?'       , 'Thal'    , '?'       , 'LS'  , 'LS' };
% ttPosition.h7.YYYYMMDD20180806  = {  'Str', 'SI'  , 'Str', 'Str', 'Str', 'CA1', 'Str', 'Str', '?'  , 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', '?'   , 'CA1' , 'CA1' , 'CA1' , 'CA1' , '?'   , 'CA1' , 'LS'  , 'Thal' , '?'       , 'Thal'    , 'Thal'    , '?'       , 'LS'  , 'LS' };
% ttPosition.h7.YYYYMMDD20180807  = {  'Str', 'HDB' , 'Str', 'Str', 'Str', 'CA1', 'Str', 'Str', '?'  , 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', '?'   , '?'   , 'CA1' , 'CA1' , 'CA1' , '?'   , '?'   , 'LS'  , 'Thal' , 'hypoThal', '?'       , 'Thal'    , '?'       , '?'   , 'LS' };
% ttPosition.h7.YYYYMMDD20180808  = {  'Str', 'HDB' , '?'  , '?'  , 'Str', 'CA1', 'Str', 'Str', 'Str', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', '?'   , '?'   , 'CA1' , 'CA1' , 'CA1' , '?'   , '?'   , 'LS'  , 'Thal' , 'hypoThal', '?'       , 'Thal'    , 'hypoThal', 'LS'  , 'LS' };
% ttPosition.h7.YYYYMMDD20180809  = {  'Str', '?'   , 'Str', 'Str', 'Str', 'CA1', 'Str', 'Str', 'Str', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', '?'   , '?'   , 'CA1' , '?'   , '?'   , '?'   , 'CA1' , 'LS'  , 'Thal' , 'hypoThal', '?'       , '?'       , '?'       , 'LS'  , 'LS' };
% ttPosition.h7.YYYYMMDD20180810  = {  'Str', 'HDB' , 'Str', 'Str', 'Str', 'CA1', 'Str', '?'  , 'Str', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', '?'   , '?'   , 'CA1' , 'CA1' , 'CA1' , '?'   , '?'   , 'LS'  , 'Thal' , '?'       , '?'       , 'Thal'    , 'hypoThal', 'LS'  , 'LS' };
% ttPosition.h7.YYYYMMDD20180813  = {  'Str', 'HDB' , 'Str', 'Str', 'Str', '?'  , 'Str', '?'  , 'Str', '?'  , 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', '?'   , '?'   , 'CA1' , 'CA1' , 'CA1' , '?'   , '?'   , 'LS'  , 'Thal' , 'hypoThal', 'Thal'    , 'Thal'    , 'hypoThal', 'LS'  , 'LS' };
% ttPosition.h7.YYYYMMDD20180814  = {  'Str', '?'   , 'Str', '?'  , 'Str', '?'  , '?'  , '?'  , 'Str', '?'  , 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', '?'   , '?'   , '?'   , 'CA1' , 'CA1' , '?'   , 'CA1' , 'LS'  , 'Thal' , '?'       , '?'       , '?'       , 'hypoThal', 'LS'  , 'LS' };
% ttPosition.h7.YYYYMMDD20180815  = {  'Str', 'HDB' , 'Str', 'Str', 'Str', 'CA1', 'Str', '?'  , 'Str', '?'  , 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', '?'  , 'CA1', '?'   , '?'   , '?'   , 'CA1' , 'CA1' , '?'   , 'CA1' , 'LS'  , 'Thal' , '?'       , '?'       , '?'       , 'hypoThal', '?'   , 'LS' };
% ttPosition.h7.YYYYMMDD20180822  = {  'Str', 'HDB' , 'Str', 'Str', 'Str', 'CA1', 'Str', 'Str', 'Str', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', '?'   , 'CA1' , 'CA1' , 'CA1' , 'CA1' , 'CA1' , 'CA1' , 'LS'  , 'Thal' , 'hypoThal', 'hypoThal', 'hypoThal', 'hypoThal', 'LS'  , 'LS' };
% ttPosition.h7.YYYYMMDD20180827  = {  '?'  , '?'   , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'   , '?'   , '?'   , '?'   , '?'   , '?'   , '?'   , '?'   , '?'    , '?'       , '?'       , '?'       , '?'       , '?'   , '?'  };
% ttPosition.h7.YYYYMMDD20180828  = {  'Str', 'HDB' , 'Str', 'Str', '?'  , '?'  , 'Str', 'Str', 'Str', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', '?'   , '?'   , '?'   , 'CA1' , 'CA1' , 'CA1' , 'CA1' , 'LS'  , '?'    , '?'       , 'hypoThal', 'hypoThal', 'hypoThal', 'LS'  , 'LS' };
% ttPosition.h7.YYYYMMDD20180831  = {  '?'  , '?'   , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', '?'   , '?'   , '?'   , '?'   , '?'   , '?'   , 'CA1' , 'LS'  , '?'    , '?'       , '?'       , '?'       , '?'       , 'LS'  , 'LS' };
% ttPosition.h7.YYYYMMDD20180904  = {  'Str', 'HDB' , 'Str', 'Str', '?'  , 'CA1', 'Str', 'Str', 'Str', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', '?'  , '?'  , '?'   , '?'   , 'CA1' , '?'   , '?'   , 'CA1' , 'CA1' , 'LS'  , 'Thal' , 'hypoThal', 'hypoThal', 'hypoThal', 'hypoThal', 'LS'  , 'LS' };
% ttPosition.h7.YYYYMMDD20180905  = {  '?'  , '?'   , '?'  , '?'  , '?'  , '?'  , '?'  , '?'  , 'Str', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', 'CA1', '?'   , '?'   , 'CA1' , '?'   , '?'   , '?'   , 'CA1' , 'LS'  , '?'    , '?'       , '?'       , '?'       , '?'       , '?'   , '?'  };
% 
% 
% 
% ttPosition.h1.YYYYMMDD20180809  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.h1.YYYYMMDD20180810  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.h1.YYYYMMDD20180813  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.h1.YYYYMMDD20180814  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.h1.YYYYMMDD20180815  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.h1.YYYYMMDD20180817  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.h1.YYYYMMDD20180822  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.h1.YYYYMMDD20180823  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.h1.YYYYMMDD20180824  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.h1.YYYYMMDD20180827a = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.h1.YYYYMMDD20180827b = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.h1.YYYYMMDD20180828  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.h1.YYYYMMDD20180829  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.h1.YYYYMMDD20180830  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.h1.YYYYMMDD20180831  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.h1.YYYYMMDD20180904  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.h1.YYYYMMDD20180905  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.h1.YYYYMMDD20180906  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.h1.YYYYMMDD20180908  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.h1.YYYYMMDD20180909  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.h1.YYYYMMDD20180914  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% 
% 
% ttPosition.da10.YYYYMMDD20170911  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.da10.YYYYMMDD20170911b = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.da10.YYYYMMDD20170912  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.da10.YYYYMMDD20170913  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.da10.YYYYMMDD20170914  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.da10.YYYYMMDD20170915  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.da10.YYYYMMDD20170918  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.da10.YYYYMMDD20170919  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.da10.YYYYMMDD20170920  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.da10.YYYYMMDD20170920b = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.da10.YYYYMMDD20170922  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.da10.YYYYMMDD20170925  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% 
% 
% ttPosition.da5.YYYYMMDD20160822  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.da5.YYYYMMDD20160823  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.da5.YYYYMMDD20160824  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.da5.YYYYMMDD20160825  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.da5.YYYYMMDD20160826  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.da5.YYYYMMDD20160827  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.da5.YYYYMMDD20160828  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.da5.YYYYMMDD20160829  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.da5.YYYYMMDD20160830  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.da5.YYYYMMDD20160831  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.da5.YYYYMMDD20160901  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.da5.YYYYMMDD20160902  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.da5.YYYYMMDD20160906  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.da5.YYYYMMDD20160907  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
% ttPosition.da5.YYYYMMDD20160908  = { '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' };
